### ISSUE TITLE
Split hubs.yaml into a directory of YAML files

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#124]
Our `hubs.yaml` file is getting a bit too big & unwieldy. It should be a set of files in a directory that are merged together with clear rules.

**Comment by choldgraf** [comment]
Yeah +1 from me - I agree it's disorienting to scroll down through a huge YAML each time I wanna change something :-). I wonder what is a natural "split point" for the file...

**Comment by yuvipanda** [comment]
Proposed directory structure:

```
- <cluster-1-name>/
  - cluster-info.yaml
  - hubs/
    - hub1.yaml
    - hub2.yaml
- <cluster-2-name>/
  - cluster-info.yaml
  - hubs/
    - hub3.yaml
    - hub4.yaml
```

`cluster-info.yaml` can contain information about where the cluster is - cloud provider, keys, image location, etc.

**Comment by choldgraf** [comment]
I like it, easy to quickly browse through it, can quickly look at cluster-wide defaults, and I assume each hub could override those defaults on its own.

 Would it make sense to have some kind of global config that is overridden at the cluster level?

**Comment by yuvipanda** [comment]
With #352 we now have a directory with 1 file per cluster.

**Comment by damianavila** [comment]
Do you want to keep it open to be more fine-grained and have 1 file per hub at the end?

**Comment by yuvipanda** [comment]
@damianavila let's close this for now, we will probably end up refactoring this as part of https://github.com/2i2c-org/pilot-hubs/issues/362
