### ISSUE TITLE
Establish an auth0 account

### ISSUE THREAD

**Issue by colliand** [2i2c-org/pilot-hubs#14]
![screen](https://wwejubwfy.s3.amazonaws.com/Sign_In_with_Auth0_2020-09-30_11-41-05.png)

**Comment by choldgraf** [comment]
**Update**: I've contacted Auth0 about getting a non-profit discount for their services:

https://auth0.com/social-impact/

Will report back if I hear from them

**Comment by yuvipanda** [comment]
Thanks a lot, @choldgraf!

**Comment by yuvipanda** [comment]
I think we can make only one more hub before we run out of this limit, so slightly more urgency here

**Comment by yuvipanda** [comment]
https://auth0.com/docs/policies/entity-limit-policy

The limit is 10 for the free account, and 100 for the cheaper paid accounts.

**Comment by choldgraf** [comment]
Hey all - I met with Alyssa, the rep from Auth0 today. 

For reference, here's their pricing page:

https://auth0.com/pricing/

A few takeaways:

- The non-profit discount is 30-50% off of the **enterprise plan**.
- So it mostly makes sense if we need enterprise features.
- The biggest benefit you'd get for this sounds like it'd be
   1. Support
   2. More deployments of `Auth0`-hosted databases
- There is also an open-source plan that is more like a heavy-powered "developer" plan
- I think we'd qualify for either the non-profit or the open-source plan

I think that the non-profit plan is still an "in the future" thing for us-  we're not at enterprise-grade size yet and it is *much* more expensive than $23 a month (even at 50% off).

The open-source plan could be a good option *if* @yuvipanda thinks it'll work for our needs. So I'll link it here once I've got the details.

If neither of those work, our best bet is to pay the $23 a month for the developer plan.

Lemme know if y'all have thoughts!

**Comment by yuvipanda** [comment]
Ah, that sounds like one of those 'non-commercial open source' license requirements. For example, (4) is impossible to predict or control, and neither is (2). Like even for something like Jupyter core, it's unfeasible, since it'll be definitely used by companies to generate revenue...

I'd say let's pay for a developer license right now - with the Howard deployment, we can at most have one more hub now. Then we can explore the FOSS option maybe?

Thanks for looking into it, @choldgraf!

**Comment by yuvipanda** [comment]
We're at the limit now, and need a paid account to add new hubs.

On the plus side, this means we're now at 10 hubs :D

@choldgraf, do you think we can just put this on your credit card again? <3

**Comment by choldgraf** [comment]
sounds good, and will do 👍  I agree that the ambiguity of the "open source" plan is probably best-dealt with by just paying them haha, it's not _that_ much

**Comment by choldgraf** [comment]
OK @yuvipanda and @colliand - I just set up an `Auth0` account for an organization called `2i2c`. It's technically a "company" account, I don't know the differences there but my other option was "personal" and that didn't seem right.

Currently we have the "free" plan with a 22 day trial window. I can buy the more expensive plan but wasn't sure which one to get. I assume we want the "Developer" plan, is that right @yuvipanda ? Maybe in the meantime the 22 day trial will get us the features we need?
