### ISSUE TITLE
Restore nbresuse memory usage indicator on Catalyst pilot hub

### ISSUE THREAD

**Issue by zaneselvans** [2i2c-org/pilot-hubs#143]
For some reason the memory usage indicator from `nbresuse` that was previously displayed on the [Catalyst Cooperative pilot hub](https://catalyst-cooperative.pilot.2i2c.cloud) seems to have vanished, and I'm also running out of memory (I think, the kernels are dying anyway) while testing our tutorial notebooks, so it would be nice to get it back.

Hopefully we can get our own Docker image building soon.

**Comment by zaneselvans** [comment]
I shut down my server and logged out, re-authenticated and started up a server and a notebook, but still not seeing any memory usage indicator. I tried installing `jupyter-resource-usage` on my local machine as well and also didn't get an indicator in my local notebooks so maybe I'm misunderstanding how one gets this information displayed. I didn't see anything related in any of the menu items or plugin manager. Now I'm wondering if this is some kind of jupyterlab 2 vs. 3 issue. Blurgh.

**Comment by choldgraf** [comment]
hmmm - let's re-open this one until we can get confirmation that the extension is back and works as-expected 👍

**Comment by zaneselvans** [comment]
Locally I seem to have both the server and notebook/lab extensions installed and enabled, but still not seeing any output in the JupyterLab interface. Feeling confused. :confused: 
```
$ jupyter serverextension list
config dir: /home/zane/miniconda3/envs/pudl-dev/etc/jupyter
    jupyter_resource_usage  enabled 
    - Validating...
      jupyter_resource_usage  OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.2.9 OK
    nbdime  enabled 
    - Validating...
      nbdime 2.1.0 OK
$ jupyter labextension list
JupyterLab v2.2.9
Known labextensions:
   app dir: /home/zane/miniconda3/envs/pudl-dev/share/jupyter/lab
        @axlair/jupyterlab_vim v0.12.4  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        nbdime-jupyterlab v2.0.1  enabled  OK
$ jupyter nbextension list
Known nbextensions:
  config dir: /home/zane/.jupyter/nbconfig
    notebook section
      vim_binding/vim_binding  enabled 
      - Validating: OK
  config dir: /home/zane/miniconda3/envs/pudl-dev/etc/jupyter/nbconfig
    notebook section
      jupyter_resource_usage/main  enabled 
      - Validating: OK
      nbdime/index  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
```

**Comment by yuvipanda** [comment]
3

**Comment by bolliger32** [comment]
Hi everyone - lurking on this thread b/c I came across a similar issue in a totally different hub setting. I believe based on their [changelog](https://github.com/jupyter-server/jupyter-resource-usage/blob/master/CHANGELOG.md#migrating-to-050) that you might need to pin to nbresuse 0.3.6 until JupyterLab 3. @yuvipanda you would know better though.

**Comment by yuvipanda** [comment]
Hmm, not sure why #146 didn't fix it. I'll look at it tomorrow again :|

**Comment by zaneselvans** [comment]
Well, glad it's not just me that can't get it to show up! Thanks for looking into it.

**Comment by yuvipanda** [comment]
I think #147 fixed this - I can see the indicator now.

<img width="230" alt="image" src="https://user-images.githubusercontent.com/30430/102879108-4be09480-446f-11eb-809e-2c3d96a5304c.png">
