### ISSUE TITLE
Explicitly shut down health-check notebooks once we are done

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#151]
If a health check fails, it leaves behind the notebook pod:

```
jupyter-service-2dhub-2dhealth-2d79a9a58b-2dca17-2d4e53-2d9a0d-2dd8cdfb961744   0/1     ImagePullBackOff   0          67m
jupyter-service-2dhub-2dhealth-2daa8a2b77-2df8d0-2d4425-2d8a79-2dc8e9e3e59ed5   0/1     ImagePullBackOff   0          17h
jupyter-service-2dhub-2dhealth-2ddb60e157-2de938-2d4f83-2d8501-2ddd8d1ea5e506   0/1     ImagePullBackOff   0          66m
proxy-7f86b75776-znflx                                                          1/1     Running            0          62m
```

We should make sure we delete these, and possibly the hub user as well.

**Comment by yuvipanda** [comment]
@GeorgianaElena this is done, right?

**Comment by GeorgianaElena** [comment]
Yes, they are shut down when there's no timeout error. If there is, then they are killed next time we do a health check.
Now we're only leaving users behind.

I should document this!!! :spiral_notepad:

**Comment by yuvipanda** [comment]
@GeorgianaElena yep! I opened https://github.com/2i2c-org/pilot-hubs/issues/234 to track documentation.
