### ISSUE TITLE
How are environments specified?

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#16]
How shall people specify the environments for each hub? I guess we'll ask people to just tell us packages that they need installed and we just build a docker image for them using repo2docker (and manually specify the image in the `hubs.yaml` file?)

In addition, what happens when somebody installs libraries within their session? Does it persist over time?

Basically, I think we should add a section [to the usage docs](https://2i2c.org/pilot/use.html) about how to customize the environment, and trying to figure out both the workflow of the user and the administrator.

**Comment by yuvipanda** [comment]
I just pushed a base image to https://github.com/2i2c-org/low-touch-hubs/tree/master/image.

I think my current plan is to have one base image for all low-touch hubs, with customizations *on top* of that image being possible. I also wanna allow users the opportunity to build their own docker image, but trying to figure out the best way to do that.

**Comment by choldgraf** [comment]
ah gotcha - so I guess the question is "how do those customizations happen?". Do they require the hub users to open issues that we manually change? (and if so, how do we change them so that others on the team can help out instead of just you!). Just trying to un-bottleneck knowledge here :-)

also cross-linking https://github.com/plasmabio/tljh-repo2docker which @yuvipanda mentioned could be a nice solution to letting others build their own image.

**Comment by yuvipanda** [comment]
Documented in  https://2i2c.org/pilot-hubs/#updating-environment for now.

**Comment by choldgraf** [comment]
nice - I'll close this 👍
