### ISSUE TITLE
Document how hub templates work

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#162]
From @choldgraf on slack:

> why did we have to change the jupyterhub config?
> specifically it looks like the config had to be nested one level deeper?

This is from the work on template hubs, and we should document this.

**Comment by GeorgianaElena** [comment]
I believe we already added some info about the templates in this PR: https://github.com/2i2c-org/pilot-hubs/pull/128 but didn't link it to this issue unfortunately. It doesn't cover the daskhub template though, so we should add info about it too before closing the issue.
