### ISSUE TITLE
Document how to use manual username/passwords

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#17]
Is it possible to use manual usernames/passwords with `auth0`? E.g., a "firstuseauthenticator"?

**Comment by yuvipanda** [comment]
@choldgraf possibly, but I really want us to discourage that - using Google Accounts (or similar) as an alternative instead. Where would you see that falling down vs manual usernames / passwords?

**Comment by choldgraf** [comment]
Hmm well the use-case that made me think about this was this person in the Netherlands who has a university email address but I'm pretty sure it's not a Google email address. I think it's probably fine to just ask them to use a GitHub username, but I suspect especially outside of the states it will be less-common for people to use GMail.

**Comment by yuvipanda** [comment]
@choldgraf makes sense! I think for now, we should just ask for GitHub usernames, but make something else available if they protest.

**Comment by choldgraf** [comment]
This is not possible currently, so I'm going to close it an open a new issue about making it possible!
