### ISSUE TITLE
Setup a hub for Julien Emile-Geay / USC Hackathon

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#172]
Linked from https://github.com/2i2c-org/meta/issues/111 (process change will come from https://github.com/2i2c-org/team-compass/pull/23)

Dates: Hackathon is on 4-5 February. 

- [x] Have a basic hub running at paleohack2021.pilot.2i2c.cloud with the default settings. Once this is done, we can let them start trying it out.
- [x] Work with the paleohack folks in building their own docker image, so we can use that instead of our base image. Let's work with them through the next week and nail this down. Shouldn't be too difficult.
- [x] Work with them to offer home page customizations
- [ ] Figure out how billing should work. This probably involves creating a new google cloud project and setting up stuff there. Exploration of this should start asap, since there is probably gonna be issues around quotas.

Our first hackathon hub! Let's use this to figure out a process that will work for future workshops

**Comment by choldgraf** [comment]
Yes! Process process process :-) I think a few products should come out of this, other than the hub infrastructure itself:

- [ ] A post-mortem of notes about how this process went
- [ ] A check-list that we can add to a template somewhere that covers the major things we needed to do
- [ ] An estimate of how much work it took us to deploy, and how we can reduce this in the future

**Comment by yuvipanda** [comment]
So there's a postmortem at https://github.com/2i2c-org/pilot-hubs/issues/260.
