### ISSUE TITLE
Setup a hub for Mills College

### ISSUE THREAD

**Issue by aculich** [2i2c-org/pilot-hubs#178]
Deadline: Should be done by 27th Wednesday, users will start using it first week of February

Where it'll run: Cloudbank

Image: Default image we use, no customizations needed

Interface: Jupyter Notebook

Authentication: Google Auth, but restricted to mills college

Domain: datahub.mills.edu (or something similar)

Current github repo: https://github.com/dlab-projects/iuse-mills-hub-deployment

Plan:

- [x] Create a hub in the cloudbank cluster (via hubs.yaml), available at https://mills.cloudbank.2i2c.cloud. 
- [x] Setup Google Auth (via auth0) in such a way that only users with mills.edu google accounts can login.
- [x] Add a CNAME from datahub.mills.edu pointing to mills.cloudbank.2i2c.cloud. This makes sure that jupyter.mills.edu is pointing to the right cluster regardless of what the IP itself is - since the IP can change if we move clusters
- [x] Once the DNS resolves, Add datahub.mills.edu as an ingress domain for this hub, so it'll set up automatic HTTPS.
- [x] Add instructors as admin users akonrad and wang both from @mills.edu addresses
- [ ] Add a private folder structure only readable/writeable by the admins (instructors) of this hub

**Comment by yuvipanda** [comment]
I've edited the issue body to list our plan.

We should also document this as we go! There's already docs at https://2i2c.org/pilot-hubs/, but I don't think there are instructions on restricting auth by domain, or on custom domains.

The current config repo for mills has a z2jh [config.yaml](https://github.com/dlab-projects/iuse-mills-hub-deployment/blob/master/config.yaml) file that might be useful - although most of the things specified there are already taken care of by hubs.yaml / deploy.py.

**Comment by GeorgianaElena** [comment]
> We should also document this as we go! There's already docs at https://2i2c.org/pilot-hubs/, but I don't think there are instructions on restricting auth by domain, or on custom domains.

@yuvipanda, this should be achievable using `hosted_domains`(https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/authentication.html#google) config option, right?

**Comment by yuvipanda** [comment]
@GeorgianaElena ah, but we're using auth0 for all our authentication needs - see [here]https://github.com/2i2c-org/pilot-hubs/blob/master/auth.py) and [here](https://github.com/2i2c-org/pilot-hubs/blob/master/hub.py#L235).

**Comment by yuvipanda** [comment]
I just realized you can do the domain name restriction with `c.Authenticator.username_pattern`. Make a regex that only matches `\@mills\.edu$` should do the trick.

However, we *should* use auth0 rules instead. But we can use username_pattern first to get this going, and do fully automated auth0 rules later.

**Comment by yuvipanda** [comment]
And if you remove the list of users in hubs.yaml, anyone who can successfully authenticate can login. So this would be *anyone* with a Google account, where the email matches the username_pattern. Good enough for us to start with.

**Comment by yuvipanda** [comment]
@aculich any updates on the CNAME from their IT? Folks can use it at the current URL already though - all work will be kept even after we move domains.

**Comment by aculich** [comment]
@yuvipanda I think Mills IT is waiting to hear back about the fix for the
vulnerability they detected:

It appears that you have a medium level vulnerability on your new server.
> Based on our security scans, the server is running version 3.4.1 of JQuery
> which is susceptible to cross site scripting. The recommendation is to
> upgrade to version 3.5.1 which is the latest available or at least to 3.5.0
> which has the above vulnerability patched.


I don't see a response back to them letting them know it has been fixed, so
I expect they are waiting to hear back about that before setting up the
CNAME.

Can you point me to the fix for the vulnerability and then
either @GeorgianaElena can reply to them to take the next step.

**Comment by GeorgianaElena** [comment]
Hey @aculich :wave: With the vulnerability now fixed and the CNAME entry added (both `datahub.mills.edu` and `mills.cloudbank.2i2c.cloud` are pointing to the same hub), I believe all the check boxes have been ticked :heart: 

Let me know if there's anything else I should do, or people that I should send the good news to :D :tada:

**Comment by aculich** [comment]
@GeorgianaElena thanks! There are two other things that we need:

- [ ] add instructors as admin users `akonrad` and `wang` both from @mills.edu addresses
- [ ] add a `shared-private` folder structure only readable/writeable by the admins (instructors) of this hub

**Comment by yuvipanda** [comment]
@aculich where are we at for this now?

**Comment by yuvipanda** [comment]
I'm going to close this as completed, please reopen if we need to do more things here, @aculich
