### ISSUE TITLE
Catalyst hub OAuth failing with 400: Bad Request

### ISSUE THREAD

**Issue by zaneselvans** [2i2c-org/pilot-hubs#180]
When trying to log in to https://catalyst-cooperative.pilot.2i2c.cloud/ I'm getting an error during the authentication process, after choosing which Google ID I want to authenticate with:

# 400 : Bad Request

**Comment by GeorgianaElena** [comment]
Hey @zaneselvans! It was my mistake, sorry about that!

I played around setting up Auth0 rules for a different hub and somehow managed to mess up the authentication for all the hubs :'(

It should be working now, but please let me know if you're still experiencing this issue. Thank you!

**Comment by zaneselvans** [comment]
It's back to working fine now. Thanks!
