### ISSUE TITLE
Upgrade to z2jh 0.11

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#183]
We're currently on z2jh 0.9. There are a lot of improvements, security & otherwise, in v0.11 - we should upgrade.

**Comment by yuvipanda** [comment]
Ref #194

**Comment by GeorgianaElena** [comment]
This should be solved by  https://github.com/2i2c-org/pilot-hubs/pull/194 and https://github.com/2i2c-org/pilot-hubs/pull/194.
