### ISSUE TITLE
Document how to set up GitHub authentication by GH organization membership

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#187]
In the Farallon Hub we have a setup where users can log in to the hub if they are a **public member** of a GitHub organization. We should document how this was set up, how to do the same for other hubs, and "gotchas" that are important to keep in mind such as "the person's membership must be public".

**Comment by yuvipanda** [comment]
When we moved farallon hub to this repo, it lost the ability to login via GitHub orgs / teams. https://github.com/2i2c-org/pilot-hubs/issues/625 and https://github.com/2i2c-org/pilot-hubs/issues/598 track this feature.
