### ISSUE TITLE
How to delete hubs?

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#20]
I noticed that when I deleted my test hub from the `hubs.yml` it didn't show up in the GHA logs at all, which I guess makes sense, but it makes me wonder if/how we handle deleting hubs so that the helm namespace doesn't become cluttered with a buncha cruft over time.

**Comment by yuvipanda** [comment]
Process for this would be:

1. Backup the `jupyterhub.sqlite` db off the hub.
2. Backup the home directory contents if we wanna.
3. Run `helm -n <hub-name> delete <hub-name>`.
4. If the hub hasn't been recreated anywhere, remove the entry from auth0.com
