### ISSUE TITLE
A few new hub deployments

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#218]
In a recent conversation, @yuvipanda and I discussed that we should just start deploying hubs for people that are interested (unless the hubs would be prohibitively expensive). We don't want paperwork to get in the way of serving users, and in these early days we have a bit of runway and flexibility to do work pro-bono in order to generate interest, gain experience (and eventually lead to a sale, since these are folks who *want* to spend money but we just haven't finished the paperwork).

I put together a `needs:hub` label in our leads repository, here's a link: https://github.com/2i2c-org/leads/labels/needs%3Ahub

Could we start off by creating a JupyterHub for each of the issues that we have listed there? What do you think @yuvipanda

**Comment by yuvipanda** [comment]
Based on our conversation today @choldgraf, I think you're gonna try create one of these :) LMK how it goes?

**Comment by choldgraf** [comment]
I think I did it here, we'll see if it actually worked haha: https://github.com/2i2c-org/pilot-hubs/pull/237

**Comment by choldgraf** [comment]
erm, something seems to have gone wrong. I'm going to roll back #237 

Here's the error, seems to be something with SSL? https://github.com/2i2c-org/pilot-hubs/runs/1922800957?check_suite_focus=true#step:10:341

**Comment by choldgraf** [comment]
closing this as we are tracking this in many other places
