### ISSUE TITLE
Run through our internal hub cost estimates

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#219]
Right now, we have very conservative estimates of how much labor it will take to run hub infrastructure. We should look at these estimates, and try to refine the numbers so that we can give reasonable prices.

# What goes into labor?

- Initial conversations about what is needed for a hub
- Initial deployment of the hub
- Customization of the hub beyond default environments
- Ongoing maintenance of hubs, that may or may not be tied directly to a single hub
- *Dedicated* maintenance for a given hub (e.g., being asked to change the environment)
- User support for a given hub (e.g., being asked a question about the hub, or a perceived outage)

# What hub types to consider

Below I'll list a few types of hubs, a brief description, and a **totally arbitrary** estimation of "days per month" for development and operations. We should discuss these days/month and get to a number that is more realistic!

| Hub Type        | User                                                                                                     | Description                                              | Dev Days / Month | Ops Days / Month |
|-----------------|----------------------------------------------------------------------------------------------------------|----------------------------------------------------------|------------------|------------------|
| Education Light | This is the most basic hub we have. Simple data science environment with minimal resources for students. | small or basic class                                     |              0.1 |             0.25 |
| Education Full  | This is a more complex educational environment (e.g., with more packages, autograding, etc)              | complex or large class                                   |              4 |              4 |
| Research Light  | "basic data science environment". Think "The PyData Stack" but nothing extremely complex.                | Lab/Team with modest funds or that needs a minimal envt. |              0.5 |                1 |
| Research Pangeo | research light + some more complex and scalable infrastructure like Dask Kubernetes                      | Lab/Team with larger datasets and more complex needs     |                4 |                4 |

**Comment by yuvipanda** [comment]
@choldgraf I've updated the numbers! I think the list of things you stated make sense. I'm not entirely sure having hours like this is the best way to go, but let's try it out and see where it takes us?

**Comment by choldgraf** [comment]
@yuvipanda just a note that this is *days* per month, not *hours*. So `1 day ~= 5-6 hours`. Does that change your opinion?

I agree this probably isn't the best way of thinking about our own internal costs, but we need some way to estimate "how many hubs can we take on, given our engineering team, before we start to hit capacity". I'm not sure how else to go about estimating this :-/

**Comment by choldgraf** [comment]
closing this as it no longer reflects how we're currently thinking about costs and pricing, and it's unclear if this is a good way to break down our costs
