### ISSUE TITLE
Add a template for the login page

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#22]
I think that we could use a slightly customized login page to highlight that 2i2c is the organization providing the hub. Nothing as fancy as the U. Toronto Hub, but I wonder if we could use two fields in the `hubs.yaml` file that would interpolate into a login template we use to build hubs:

```
- long_name: A longer name used for displaying in other pages
- logo: A path/URL to a logo
```

Then we could have a login page template that included bits like:

```
                    {logo}
This is a 2i2c Pilot Hub provided for {long_name}.
        Click the button below to log-in.
    For more information, see 2i2c.org/pilot
```

**Comment by yuvipanda** [comment]
Great idea, @choldgraf. We can definitely pass those template variables through. Do you think you can fork https://github.com/utoronto-2i2c/homepage and make a quick repo, and I'll set it up as the front page?

**Comment by choldgraf** [comment]
I was thinking something like this:

https://github.com/utoronto-2i2c/homepage/pull/1/files

It pulls the same fields that are used to populate the table here: https://2i2c.org/pilot/infrastructure.html#a-list-of-current-hubs
I wasn't sure how to demo this, so we probably want to tweak the CSS etc. If you provide some documentation for how I can actually render this then I can also try working the CSS to improve the look.

Also wasn't sure if we wanted to include the buttons etc that Toronto uses, though I think all the same interfaces are installed?

**Comment by yuvipanda** [comment]
I merged your changes into https://github.com/2i2c-org/pilot-homepage. I also
added instructions on local testing. That should help locally test this - do
you think you can try that out?

I think including the interface buttons is a great idea. If we can template
all these things appropriately, we can also just use the same homepage for
UToronto as well. But maybe that can wait?

**Comment by choldgraf** [comment]
I think that right now we should shoot for MVP of a page that at least has the name of the target org on it, and we can think about streamlining / templating more carefully after that. Does that make sense?

I'll take a stab at demoing locally!
