### ISSUE TITLE
Hubs have leftover users from support jobs?

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#221]
I noticed in the SBCC hub that there are a bunch of bot users:

![image](https://user-images.githubusercontent.com/1839645/107686841-8dfda980-6c5a-11eb-83f6-fe90b9d8e2ac.png)

I assume those are leftover from previous load tests etc, and that we can delete them?

**Comment by yuvipanda** [comment]
Yep, leftovers from before #196. You can delete these!

**Comment by yuvipanda** [comment]
#196 should take care of this.
