### ISSUE TITLE
Second login of an admin causes login failure

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#222]
I investigated https://github.com/2i2c-org/pilot/issues/45 and found the following error message:

<details>
[W 2021-02-11 17:48:29.750 JupyterHub user:681] nfguebels@pipeline.sbcc.edu's server failed to start in 600 seconds, giving up
[I 2021-02-11 17:48:29.752 JupyterHub spawner:1997] Deleting pod jupyter-nfguebels-40pipeline-2esbcc-2eedu
[E 2021-02-11 17:48:39.709 JupyterHub gen:623] Exception in Future <Task finished name='Task-1191' coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py:895> exception=TimeoutError('Timeout')> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 618, in error_callback
        future.result()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 902, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 707, in spawn
        raise e
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 606, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
    tornado.util.TimeoutError: Timeout
    
[I 2021-02-11 17:48:52.552 JupyterHub log:181] 200 GET /hub/metrics (@10.52.1.50) 7.33ms
[I 2021-02-11 17:49:06.266 JupyterHub proxy:319] Checking routes
[E 2021-02-11 17:49:17.157 JupyterHub spawner:1961] Pod jupyter-nfguebels-40pipeline-2esbcc-2eedu never showed up in reflector, restarting pod reflector
[I 2021-02-11 17:49:17.164 JupyterHub reflector:201] watching for pods with label selector='component=singleuser-server' in namespace sbcc
[E 2021-02-11 17:49:17.164 JupyterHub gen:623] Exception in Future <Task finished name='Task-1192' coro=<KubeSpawner._start() done, defined at /usr/local/lib/python3.8/dist-packages/kubespawner/spawner.py:1906> exception=TimeoutError('pod/jupyter-nfguebels-40pipeline-2esbcc-2eedu did not start in 600 seconds!')> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 618, in error_callback
        future.result()
      File "/usr/local/lib/python3.8/dist-packages/kubespawner/spawner.py", line 1952, in _start
        await exponential_backoff(
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/utils.py", line 183, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: pod/jupyter-nfguebels-40pipeline-2esbcc-2eedu did not start in 600 seconds!
</details>

This was followed by 5-6 repeats of the following

<details>
[E 2021-02-11 19:05:12.877 JupyterHub gen:623] Exception in Future <Task finished name='Task-8085' coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py:895> exception=ApiException()> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 618, in error_callback
        future.result()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 902, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 707, in spawn
        raise e
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 606, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.8/dist-packages/kubespawner/spawner.py", line 1939, in _start
        await exponential_backoff(
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/utils.py", line 168, in exponential_backoff
        ret = await maybe_future(pass_func(*args, **kwargs))
      File "/usr/local/lib/python3.8/dist-packages/kubespawner/spawner.py", line 1842, in _make_create_pod_request
        await gen.with_timeout(timedelta(seconds=request_timeout), self.asynchronize(
      File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.8/dist-packages/kubespawner/spawner.py", line 1670, in asynchronize
        return method(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api/core_v1_api.py", line 7320, in create_namespaced_pod
        return self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)  # noqa: E501
      File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api/core_v1_api.py", line 7415, in create_namespaced_pod_with_http_info
        return self.api_client.call_api(
      File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 348, in call_api
        return self.__call_api(resource_path, method,
      File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 180, in __call_api
        response_data = self.request(
      File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 391, in request
        return self.rest_client.POST(url,
      File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/rest.py", line 274, in POST
        return self.request("POST", url,
      File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/rest.py", line 233, in request
        raise ApiException(http_resp=r)
    kubernetes.client.exceptions.ApiException: (422)
    Reason: error
    HTTP response headers: HTTPHeaderDict({'Audit-Id': '2347066c-ad86-4ab8-b271-107bad5b7d81', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Thu, 11 Feb 2021 19:05:12 GMT', 'Content-Length': '1636'})
    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"jupyter-nfguebels-40pipeline-2esbcc-2eedu\" is invalid: [spec.containers[0].volumeMounts[3].mountPath: Invalid value: \"/home/jovyan/shared-readwrite\": must be unique, spec.containers[0].volumeMounts[4].mountPath: Invalid value: \"/home/jovyan/shared-readwrite\": must be unique, spec.containers[0].volumeMounts[5].mountPath: Invalid value: \"/home/jovyan/shared-readwrite\": must be unique, spec.containers[0].volumeMounts[6].mountPath: Invalid value: \"/home/jovyan/shared-readwrite\": must be unique, spec.containers[0].volumeMounts[7].mountPath: Invalid value: \"/home/jovyan/shared-readwrite\": must be unique]","reason":"Invalid","details":{"name":"jupyter-nfguebels-40pipeline-2esbcc-2eedu","kind":"Pod","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"/home/jovyan/shared-readwrite\": must be unique","field":"spec.containers[0].volumeMounts[3].mountPath"},{"reason":"FieldValueInvalid","message":"Invalid value: \"/home/jovyan/shared-readwrite\": must be unique","field":"spec.containers[0].volumeMounts[4].mountPath"},{"reason":"FieldValueInvalid","message":"Invalid value: \"/home/jovyan/shared-readwrite\": must be unique","field":"spec.containers[0].volumeMounts[5].mountPath"},{"reason":"FieldValueInvalid","message":"Invalid value: \"/home/jovyan/shared-readwrite\": must be unique","field":"spec.containers[0].volumeMounts[6].mountPath"},{"reason":"FieldValueInvalid"
c.containers[0].volumeMounts[7].mountPath"}]},"code":422}
    
    
    
[E 2021-02-11 19:05:12.985 JupyterHub pages:380] Previous spawn for nfguebels@pipeline.s
    Reason: error
    HTTP response headers: HTTPHeaderDict({'Audit-Id': '2347066c-ad86-4ab8-b271-107bad5b
Thu, 11 Feb 2021 19:05:12 GMT', 'Content-Length': '1636'})
    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failu
ers[0].volumeMounts[3].mountPath: Invalid value: \"/home/jovyan/shared-readwrite\": must
ared-readwrite\": must be unique, spec.containers[0].volumeMounts[5].mountPath: Invalid 
6].mountPath: Invalid value: \"/home/jovyan/shared-readwrite\": must be unique, spec.con
st be unique]","reason":"Invalid","details":{"name":"jupyter-nfguebels-40pipeline-2esbcc
home/jovyan/shared-readwrite\": must be unique","field":"spec.containers[0].volumeMounts
red-readwrite\": must be unique","field":"spec.containers[0].volumeMounts[4].mountPath"}
: must be unique","field":"spec.containers[0].volumeMounts[5].mountPath"},{"reason":"Fie
e","field":"spec.containers[0].volumeMounts[6].mountPath"},{"reason":"FieldValueInvalid"
c.containers[0].volumeMounts[7].mountPath"}]},"code":422}

</details>

So if a spawn fails, the spawner object seems to gets re-used and you get duplicate `volumeMounts` that are invalid. This causes repeated failures. The hub restarts itself after 5 successive failures, and so the user was able to log in after.
 
I'm not sure if the spawner object gets re-used only if the spawn fails, or all the time.
The repeated volumeMounts are likely because we are appending volumeMounts without checking if they already exist [here](https://github.com/2i2c-org/pilot-hubs/blob/643059b3f80d7678871dcfb09114328c38a6688e/hub-templates/base-hub/values.yaml#L179). We should not do that anyway - only add if it doesn't already exist.

https://github.com/jupyterhub/kubespawner/issues/468 should help with that, but we can probably also fix this locally.

closes https://github.com/2i2c-org/pilot/issues/45

**Comment by choldgraf** [comment]
Ooohhh I think this is our first bug report!

**Comment by yuvipanda** [comment]
Looking at the timestamps, the original login failed login is probably due to maintenance from https://github.com/2i2c-org/pilot-hubs/pull/223. I checked before I started that nobody was on it, but looks like the user got on just as things got back on.

**Comment by choldgraf** [comment]
This makes me wonder if it would be possible for us to serve a "2i2c Hubs are undergoing maintenance" page while upgrades etc are happening?

**Comment by yuvipanda** [comment]
@choldgraf heh, I beat you to filing that by about 30s - https://github.com/2i2c-org/pilot/issues/46. Slightly different though.

I think a 'we are under maintenance' page would be nice, and we should probably do that too. But it's more difficult - if your cluster is undergoing maintenance (as it was now!) then where will you serve your maintenance page from!?!

**Comment by yuvipanda** [comment]
Even with this though, I'm pretty happy how it turned out. The login failure required two things to happen - a config failure on our part, and maintenance. Even with that, it 'self healed' soon after. Not bad!

**Comment by yuvipanda** [comment]
We should basically check to make sure a volume with that same 'name' is already present before adding it.

**Comment by yuvipanda** [comment]
@GeorgianaElena this was fixed, right?

**Comment by GeorgianaElena** [comment]
Yes, I think this was fixed by https://github.com/2i2c-org/pilot-hubs/pull/266. Sorry for not linking this issue to the PR :disappointed:

**Comment by choldgraf** [comment]
wohoo then let's close this one 👍
