### ISSUE TITLE
Rename this repository?

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#23]
I feel like `low-touch-hubs` feels a bit underwhelming as a name. It might come across as "we don't want to put effort into these hubs", which isn't quite true, what we want is more like "we want to put a lot of careful effort into it once, now, so we don't have to put effort into it over time later".

Since we will likely direct people to this repository for the sake of "transparent infrastructure", I wonder if we should rename this to something more like "auto-hubs" or "pilot-hubs"?

or @yuvipanda feel free to tell me I am over-thinking this haha

**Comment by colliand** [comment]
Good observation. I like `pilot-hubs` at this time.

**Comment by choldgraf** [comment]
OK, repository is renamed and now the docs are at 2i2c.org/pilot-hubs

Note that I didn't have access to the readthedocs documentation so I can't delete it. @yuvipanda could you do that?

Longer term it would be good to still use readthedocs, but I'm not sure how we can easily set it up to use `2i2c.org/<repo-name>` so using github-pages for now

**Comment by choldgraf** [comment]
the hub push seemed to work too, so I'm gonna close this 👍

**Comment by yuvipanda** [comment]
PILOT HUBS! <3

I'll give you RTD access, but it looks like github-pages is already well set up.
