### ISSUE TITLE
Documentation Sprint: March 1-5, 2021

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#274]
# Background

We have a lot of undocumented capabilities right now, and it is a good time to take a pause & write them up.

# Expected timeline

This is an experiment with a time-bound goal. It's over when March 5th is over, so it's a week long effort to improve our documentation.

# Steps to complete this goal

1. Find pre-existing issues we have about writing more documentation, pick some, link them here, and write some of them.
2. Go through our current deployments, find features they have that aren't documented. Make issues for them, and write some of them.

# Links to issues / PRs as part of this goal

- [ ] #273 
- [ ] #156 
- [ ] #184 
- [x] #162
- [ ] #234

**Comment by yuvipanda** [comment]
Only #162 was done, and that was from @GeorgianaElena. I did open two big ones (https://github.com/2i2c-org/pilot-hubs/pull/293, https://github.com/2i2c-org/pilot/pull/55), not listed here. 

So maybe the goals was a success, but not just those linked here? I'm not sure what this means for time bound documentation goals.

**Comment by yuvipanda** [comment]
@GeorgianaElena @choldgraf what do you think of goals like this?

**Comment by GeorgianaElena** [comment]
For me, this goal was a really good idea. It motivated me to open those two docs PR before the deadline of this goal ended :sweat_smile: But I agree this could also be a discussion part of the the weekly team sync process where we all agree to something like "this week we'll try to make time to write docs".
