### ISSUE TITLE
Delete UToronto A records?

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#307]
We have several A records that point to U Toronto infrastructure from our `2i2c.org` URL:

![chrome_ogXYGWah8q](https://user-images.githubusercontent.com/1839645/111354909-0eda0780-8644-11eb-923c-71b26c9c6bf2.png)

What shall we do with them? I think that we want to use `2i2c.cloud` for the actual hub services. cc @yuvipanda in case he knows more about how / why these are set up.

**Comment by yuvipanda** [comment]
Ah, you are correct re: 2i2c.cloud. I've removed these A records.
