### ISSUE TITLE
Split deployment action to 1 per cluster

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#319]
Currently, we have 1 GitHub Action that deploys hubs across 3 clusters. This gets slow and frustrating.

We can make this go faster by just running the action once per cluster - perhaps with something like [build matrices](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix)?

**Comment by GeorgianaElena** [comment]
This is solved, right @yuvipanda? :tada:

**Comment by yuvipanda** [comment]
@GeorgianaElena so right now, since they're 'matrixed', we can't restart them individually - if one fails, we need to re-run all :( I think we'll need these to be 3 separate actions instead, so they can be restarted individually

**Comment by GeorgianaElena** [comment]
Oh right, [you can't restart just one failing job](https://github.community/t/re-run-jobs/16145) :(

> I think we'll need these to be 3 separate actions instead, so they can be restarted individually

Yes, I think so too. We'll end up with some duplicated code, though. But I think it's worth it.

**Comment by yuvipanda** [comment]
@GeorgianaElena can you take this on? :)

I also think you can make a github *action* that's just available in this repo, and use that for the jobs. That should avoid duplication.
