### ISSUE TITLE
Automate & document full process of setting up a new hub

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#336]
# Background

We should fully automate - and document when it can not be - the process to turn up a hub for a new organization.

# Steps to complete this goal

- [x] #335
- [ ] #332 
- [ ] #124 
- [ ] Documentation on terraform workspaces, and how we allocate them per-project
- [ ] Document options for hubs.yaml
- [ ] Document how to setup appropriate authentication mechanism for the
- [ ] Document creating a new copy of the action for each hub
-

**Comment by choldgraf** [comment]
I'm gonna close this one because I think we are tracking it across a bunch of other issues now
