### ISSUE TITLE
Delete the Peddie Hub

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#354]
# Summary

I'm pretty sure that the Peddie Academy hub isn't being used anymore - it hasn't had activity that I've seen, and I emailed the instructor that was going to be testing it out, and he didn't respond. I think that we can delete the hub.

This is the hub: https://github.com/2i2c-org/pilot-hubs/blob/master/hubs.yaml#L311

For reference: [Here are the instructions to delete a hub](https://pilot-hubs.2i2c.org/en/latest/howto/operate/delete-hub.html)

**Comment by choldgraf** [comment]
@yuvipanda if you've got a "spring cleaning" issue open or something feel free to just delete this and add a to-do item in there :-)

**Comment by damianavila** [comment]
@choldgraf looking at the pilot docs I noticed you are backing up user's data before deleting the Hub.
That makes sense but also has implications about dealing with user's data. Thinking around FERPA like stuff and the general question about what info we do maintain/keep, how long we keep it, when we destroy it, etc. Is there any discussion on that matter? Because I presume you already thought about this before. Thanks!

**Comment by yuvipanda** [comment]
@damianavila I don't think we have any useful policy around this right now, and we should before we delete this I think.

**Comment by yuvipanda** [comment]
@choldgraf although, maybe we can just delete the home dirs too this time? I do see some notebooks nbgitpull-ed in there...

**Comment by choldgraf** [comment]
I think that if the hub hasn't been used in several months, we should just delete this one. It was a pro bono that we set up just so they could experiment, and they haven't responded to my emails since

**Comment by damianavila** [comment]
I am totally OK with the decision you are going to take on this particular case, my question was essentially a general one about the policy for the upcoming deletions :wink:

**Comment by choldgraf** [comment]
I'm closing this because we don't actually want to delete this! It turns out that they actually _are_ using this infrastructure, and I had missed their activity from before.
