### ISSUE TITLE
Migrate Farallon hub to this repo

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#368]
# Background

The Farallon institute JupyterHub is run from github.com/2i2c-org/pangeo-hubs/, and is [not well automated](https://github.com/2i2c-org/pilot-hubs/discussions/365). We should move that to this repository!

https://github.com/2i2c-org/pilot-hubs/issues/366 tackles fully setting up on AWS, so this goal will focus only on migrating the *helm* config + deployment to this repository.

# Expected timeline

???

# Steps to complete this goal

- [x] Add support for a cluster authentication method that can be used on the farallon hub to `deployer/`
- [x] Move the staging farallon hub 
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/381
- [x] Figure out how to do authentication - right now, Farallon hub uses GitHub orgs for authorization, which auth0 doesn't support yet https://github.com/2i2c-org/pilot-hubs/pull/487
- [x] Move the production farallon hub
- [x] ~Consider removing the farallon staging hub~ (gonna keep it)
- [x] Archive https://github.com/2i2c-org/pangeo-hubs

**Comment by choldgraf** [comment]
Just a quick note on this - I think we should prioritize this below #363 - so I'm attaching a label to mark this as such :-)

**Comment by yuvipanda** [comment]
Once https://github.com/2i2c-org/pilot-hubs/pull/391 is merged, @damianavila is going to go through moving the farallon hub over to the new kops based setup. That will help complete this.

**Comment by damianavila** [comment]
A little reminder to re-revert https://github.com/2i2c-org/pilot-hubs/pull/400 once the above is complete.

**Comment by yuvipanda** [comment]
We should archive https://github.com/2i2c-org/pangeo-hubs once this is complete

**Comment by yuvipanda** [comment]
I've carefully deleted the old EFS instance. I'll now carefully delete the old cluster

**Comment by yuvipanda** [comment]
I've deleted the staging and prod hubs by hand:

```
helm -n farallon-staging delete farallon-staging
helm -n farallon-prod delete farallon-prod
```

This ensures that any external cloud resources created by kubernetes (disks for the hub db dir, load balancer for the `proxy-public` service) are deleted

**Comment by yuvipanda** [comment]
I've enabled EFS Lifecycles on the new EFS setup too (https://docs.aws.amazon.com/efs/latest/ug/lifecycle-management-efs.html) - this moves infrequently accessed files to slightly slower storage for significant cost benefits. The previous EFS had this enabled

**Comment by yuvipanda** [comment]
I deleted the old cluster with:

```
export KOPS_STATE_STORE=s3://2i2c-farallon-pangeo-kops
kops delete cluster farallon-2i2c.k8s.local --yes
```

**Comment by damianavila** [comment]
> This ensures that any external cloud resources created by kubernetes (disks for the hub db dir, load balancer for the proxy-public service) are deleted

I have seen this issue as well with CloudFormation stuff, particularly with the load balancer.
We should document this practice, @yuvipanda, WDYT?

**Comment by yuvipanda** [comment]
@damianavila yeah! Perhaps documented as part of decomissioning a hub / cluster?

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/pangeo-hubs is now just the user image

**Comment by damianavila** [comment]
For the record, the repo was renamed as well as `farallon-image`

**Comment by GeorgianaElena** [comment]
>> Once #391 is merged, @damianavila is going to go through moving the farallon hub over to the new kops based setup. That will help complete this.

> A little reminder to re-revert #400 once the above is complete.

I was wondering where are we with this and if it's ok to re-revevert #400?
Ref: https://github.com/2i2c-org/pilot-hubs/issues/507

**Comment by damianavila** [comment]
@GeorgianaElena, I think we need to solve https://github.com/2i2c-org/pilot-hubs/issues/381 to close this one and before revert #400.

**Comment by yuvipanda** [comment]
I'm going to close this, as the hub itself is migrated. #381 tracks the general problem that is preventing  CD from happening longer term
