### ISSUE TITLE
Use an AWS IAM Role / User to fetch kubernetes credentials in our deployer

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#381]
# Background

For AWS, we've checked in a static version of kubeconfig [exported by kops](https://github.com/2i2c-org/pilot-hubs/pull/379/commits/c81b36921307033fc6c491d3913c249993314dc3), with a 30d lifetime. Instead, we should create an AWS IAM Role with just enough permissions to run `KUBECONFIG=secrets/farallon.yaml kops export kubecfg --admin=30m farallon-2i2c.k8s.local`, and use that instead.

# Expected timeline

The credentials for farallon in https://github.com/2i2c-org/pilot-hubs/pull/379 last 30days, so this is a ticking time bomb :D

# Steps to complete this goal

- [x] Make an AWS IAM Role (or User) that can fetch kubeconfig via kops
- [x] Modify our deployer to accept the role (or user) credentials instead of checking in a static kubeconfig file

**Comment by damianavila** [comment]
Definitely! Checking in the static kubeconfig file, even when it is a quick way to do it and I think is OK for now for fast iteration, is somehow ringing 🔔  in my head 😉 .

**Comment by damianavila** [comment]
> In farallon, we would need to create a new deployer user under the 2i2c-engineers group

Created a new user:
aws iam create-user --user-name deployer

Added the user to the 2i2c-engineers group
aws iam add-user-to-group --group-name 2i2c-engineers --user-name deployer

Checked if the user was added to the group
aws iam get-group --group-name 2i2c-engineers

Got the credentials:
aws iam create-access-key --user-name deployer | tee /tmp/farallon.json

**Comment by damianavila** [comment]
So, we now have a PR for this one 😉 , #673.
