### ISSUE TITLE
Deploy common set of support components for each cluster we operate

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#388]
# Background

All clusters we operate should have a 'baseline' set of supporting services that should be deployed uniformly. This helps us administer them in one go.

| Chart | Purpose |
| - | - |
| Prometheus | Collect metrics from nodes, k8s, hub |
| nginx-ingress | Provide single external endpoint to get traffic into the cluster |
| cert-manager | Setup HTTPS via Let's Encrypt for all our services |

# Expected timeline

We already have this deployed for two of our clusters, from `support/` in this repo. We should automatically make sure this is deployed on all our clusters.

# Steps to complete this goal

- [x] Make sure our `support/` chart is up to date
- [x] Write a `deploy-support` script that'll deploy the support components for a given cluster
- [x] Auto deploy it for each cluster

**Comment by yuvipanda** [comment]
Another question here is what to do about Grafana. Should we do one per cluster? Or have a centralized one?

**Comment by choldgraf** [comment]
This one feels like an important "standardize and professionalize our deployments infrastructure" issue, so adding to the backlog

**Comment by yuvipanda** [comment]
This is done now!
