### ISSUE TITLE
palomar.cloudbank.2i2c.cloud 

### ISSUE THREAD

**Issue by ericvd-ucb** [2i2c-org/pilot-hubs#392]
# Background

Time to add a new hub for Palomar CC in San Diego on the Cloudbank Deployment 

# Setup Information

- **Hub auth type**: 
Google 

- **Hub administrators**: 
ericvd@berkeley.edu
sean.smorris@berkeley.edu
tcanon@palomar.edu
PChen@palomar.edu

- **Hub url**: 
palomar.cloudbank.2i2c.cloud 
- **Hub logo**: 

- **Hub logo URL**: 
https://www2.palomar.edu/pages/guidelines/files/2016/03/webGuide_screened_2-color_light.jpg

- **Hub type**: 
California Community College Pilot
- **Hub cluster**: 
Cloudbank
- **Hub image**: 

# Important Information

- **Link to leads issue**: 
- **Hub config name**: 
- **Community champion**: 
- **Hub start date**: 
May 12, 2021
- **Hub end date**: 
May 12, 2022
- **Hub important dates**: 
To teach in Fall semester
To onboad/ demo Friday May 14, 2021

# Deploy To Do

- [x] Initial Hub deployment
- [ ] Administrators able to log on
- [ ] Community Champion satisfied with hub environment
- [ ] Hub now in steady-state

**Comment by ericvd-ucb** [comment]
@sean-morris @yuvipanda 

Not sure how to proceed - do you want me to PR off the existing cloudbank.cluster.yaml
or is filling this Issue the new workflow
or should we have @sean-morris to the PR?

**Comment by yuvipanda** [comment]
@ericvd-ucb this might be a good test run for @sean-morris. What do you think, @sean-morris?

**Comment by sean-morris** [comment]
I can make a PR but I guess I am not gtting the workflow here, I think I might need someone to walk me through exactly what we mean by this:
"Not sure how to proceed - do you want me to PR off the existing cloudbank.cluster.yaml
or is filling this Issue the new workflow
or should we have @sean-morris to the PR?" 

I am supposed to meet with Chris today so I can check in with him on this piece.

**Comment by ericvd-ucb** [comment]
hey @sean-morris I can walk you through this  - or what I would do - as of a few months ago

Basically I would go to https://github.com/2i2c-org/pilot-hubs/blob/master/config/hubs/cloudbank.cluster.yaml

and edit the file to add a part at the bottom with the particulars of Palomar
( basically copy and pasting from an existing hub onto the bottom of the file and changing key parameters) 
and then Yuvi or Georgiana review the PR 

Eric

**Comment by yuvipanda** [comment]
I think this hub has been working well for a while now!
