### ISSUE TITLE
update admin on cloudbank hubs

### ISSUE THREAD

**Issue by ericvd-ucb** [2i2c-org/pilot-hubs#393]
# Summary

I would like to add @sean-morris as admin on the cloudbank hubs 
potentially replacing james percy as he has moved on

**Comment by GeorgianaElena** [comment]
Hey @ericvd-uc :wave:  I opened https://github.com/2i2c-org/pilot-hubs/pull/394 to fix this, but it looks like the cloudbank hubs use google for authentication. Can you (or Sean) share Sean's email address so I can add it the list?
Thank you!

**Comment by GeorgianaElena** [comment]
> Can you (or Sean) share Sean's email address so I can add it the list?

Found it in https://github.com/2i2c-org/pilot-hubs/issues/392. Sorry for the noise @ericvd-ucb :sweat_smile:
