### ISSUE TITLE
What happens if we switch auth for a pre-existing jupyterhub?

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#40]
Are users deleted? Do we error?

**Comment by yuvipanda** [comment]
GitHub users are via names, while Google ones are via email. So if you switch, the usernames will change. Their home directories will be different, but as admins they can still access the older servers and copy files over.

So, they aren't deleted - but can't be accessed if you aren't admin.

**Comment by choldgraf** [comment]
that's good to know! will document :-)

**Comment by choldgraf** [comment]
now documented here: https://2i2c.org/pilot-hubs/#authentication
