### ISSUE TITLE
Auth for Demo Hub

### ISSUE THREAD

**Issue by ericvd-ucb** [2i2c-org/pilot-hubs#404]
Should we have a (non-Google)  auth for demo.cloudbank.2i2c.cloud

 
If we are demoing with campuses - many of which have MS/Outlook email servers - its difficult to onboard people through google auth workflow

workshop.datahub.berkeley.edu has a single password auth 

is this a broader question for 2i2c to have a demo hub across 2i2c not specific to cloudbank 2i2c

@sean-morris

**Comment by yuvipanda** [comment]
@sean-morris beat you to this by a few minutes in https://github.com/2i2c-org/pilot-hubs/issues/403 :) I'll close this one to keep conversation together there.
