### ISSUE TITLE
Default branch set to master in nbgitpuller 

### ISSUE THREAD

**Issue by sean-morris** [2i2c-org/pilot-hubs#405]
# Summary

The default branch in [nbgitpuller ](https://jupyterhub.github.io/nbgitpuller/link) is set to master. Github changed the default branch name to "main" sometime in the Fall of 2020.

# User Stories

During our demo with Palomar CC, we tried to generate a link via nbgitpuller from a repository using the branch name, "master". We did not realize this was a newer repository in Github with a default branch name of "main". It might be prudent to change the default branch name in nbgitpuller to "main" or leave the field empty and force the user to specify the branch name. I suppose a more intensive solution would check the repo to ensure the branch exists.

# Important information

- [Nbgitpuller](https://jupyterhub.github.io/nbgitpuller/link)

# Tasks to complete

- [ ] Decide how intensive the solution should be - automatically check repo or just change the branch field
- [ ] Implement and redeploy

**Comment by damianavila** [comment]
@yuvipanda I think this one should be a ticket in the nbgitpuller repo. Thoughts?
And we can link that one from here... 
And this one will be centered into performing further steps to bring the "fixed" version, @sean-morris , WDYT?

**Comment by yuvipanda** [comment]
nbgitpuller has an issue already: https://github.com/jupyterhub/nbgitpuller/issues/159

Yeah, we should find a way to make this ticket 'track' getting that fix to a point where we can use it here.

**Comment by sean-morris** [comment]
"Tracking" this  [jupyterhub/nbgitpuller#159](https://github.com/jupyterhub/nbgitpuller/issues/159) would be great.  I subscribed to the issue and am watching the repo. Is there a way to "notify" this specific issue in pilot-hubs when the nbgitpuller issue is updated. It looks a solution was propsed on April 9th.

**Comment by yuvipanda** [comment]
@sean-morris do you think you'll be able to try implementing that solution and see if you can get it to work?

**Comment by sean-morris** [comment]
I am sure I could.I am trying to get a handle on this week this morning but will touch base

**Comment by yuvipanda** [comment]
@sean-morris awesome. lmk how I can help you get started?

**Comment by yuvipanda** [comment]
Should be fixed by https://github.com/jupyterhub/nbgitpuller/pull/179
