### ISSUE TITLE
Move paleohack hub to pilot hubs cluster again

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#409]
# Background

For #260 hub, we run their own cluster. The original reason was to make sure cost is separated out. However, it's barely used now - and the baseline cost is pretty high.

We should move it back to pilot-hubs repo, and decomission the project it was on. This will make our management simpler, and make things cheaper - we're paying for it anyway. 

# Steps to complete this goal

- [x] Determine how much the current hub is being used
- [x] Contact the folks who ran paleohack and figure out their expected usage
- [x] Move data over to NFS server for pilot hubs
- [x] Move DNS over to pilot hubs cluster
- [x] Decomission old cluster

**Comment by yuvipanda** [comment]
@choldgraf do you know what the status of us being able to charge people for hubs is? I'm guessing that'll affect what we do with this

**Comment by choldgraf** [comment]
Hmm, would it be much work to move it back if need be? I think the "when will we be able to accept money for hubs?" question is complicated, but in the short term I think we should be optimizing for user experience and learning, rather than for revenue. So that suggests to me it's fine to move it to pilot hubs as long as it's not a big pain

**Comment by yuvipanda** [comment]
Should be fairly easy to move back. Let's do it :)

**Comment by yuvipanda** [comment]
I'm moving data over by:

1. Creating an ssh keypair (`ssh-keygen -f key`)
2. Putting the public key in `/home/ubuntu/.ssh/authorized_keys` in the NFS server in the paleohack project
3. Putting the private key in the NFS server in the pilot hubs project, since that's where we are moving it to.
4. SCP current homedirectory contents to the appropriate NFS directory that will be used by the hub on the 2i2c cluster. This copies `/export/home-01/homes/paleohack2021` from the NFS server in the paleohack project to the same location in the 2i2c cluster. I move the old contents of this directory to _old - this is ok, since the users will now see the same contents. Make sure this is all owned by uid `1000`

**Comment by yuvipanda** [comment]
I've stopped the NFS server, and set the cluster to size to 0. I looked around and found nothing else that needs preserving. I'll wait for another week, and delete everything.

**Comment by yuvipanda** [comment]
Old cluster is gone! I went and deleted some objects manually:

1. PVCs created by the cluster
2. NFS Server
3. Cloud logging bucket

But realized that I can instead just shut down the project, so I've done that now.

**Comment by yuvipanda** [comment]
I also deleted the terraform workspace with `terraform workspace delete hackathon-2i2c-project-alpha`
