### ISSUE TITLE
Make hubs compatible with Z2JH 1.0.0

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/pilot-hubs#414]
# Background

Z2JH 1.0.0 introduce breaking changes, we must make some adjustments.

# Expected timeline

End of May.

# Steps to complete this goal

- [x] Verify outcomes of schema validation using [instructions here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2200#issuecomment-841761600).
  - [x] Verified outcomes of using `basehub` and its default values (-> relocate singleuser.admin / cloudResources)
  - [x] Verified outcomes of using `daskhub` and its default values (-> relocate singleuser.admin / cloudResources)
  - [x] Manually verified the cluster specific deployment configuration (-> relocate homepage)
- [x] Verify we work against k8s 1.17+ clusters
- [x] Verify we use a helm client versioned 3.5+
- [x] Acknowledge that deleting users will now also delete the users associated PVC
- [ ] Acknowledge that pods in the JupyterHub helm chart no longer have predefined resource requests (cpu/memory). See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2034.
- [x] Relocate `cloudResources` to `custom.cloudResources` (?) where Z2JH 1.0.0 won't complain about a passed value it doesn't recognize.
- [ ] Relocate `singleuser.admin` to `custom.singleuserAdmin` (?) where Z2JH 1.0.0 won't complain about a passed value it doesn't recognize.
- [x] Relocate `homepage` to `custom.homepage` or perhaps `global.2i2c.homepage` where Z2JH 1.0.0 won't complain about a passed value it doesn't recognize. Note that `global` variables are not made accessible from `get_config` though, but such feature would be acceptable to implement i think.

**Comment by yuvipanda** [comment]
I've verified that all our current clusters are on at least 1.19. Opened #412 to decide ongoing policy.

Our GitHub actions use https://github.com/Azure/setup-helm, which uses latest stable version of helm. So that's 3.5. 

I opened https://github.com/2i2c-org/pilot-hubs/pull/415 for custom.cloudResources. I've some more thinking to do for singleuser.admin.

**Comment by consideRatio** [comment]
@yuvipanda I scanned the cluster specific configs and found `jupyterhub.homepage` was referenced as well - that will also cause issues.

**Comment by yuvipanda** [comment]
#417 just moved home page stuff under custom, I think that's good enough for now.

**Comment by yuvipanda** [comment]
> I've some more thinking to do for singleuser.admin.

We should just move it under custom for now I think
