### ISSUE TITLE
Logging out of demo hub does not actually log you out

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#422]
## Steps to reproduce

1. Log in to [demo hub](https://demo.cloudbank.2i2c.cloud)
2. Once server starts, log out
3. Click the login button again

## Expected result

I'm taken to a screen that asks me to provide username / password to log in

## Actual result

I'm logged in automatically!

## How to fix?

Auth0 has documentation about the [various levels of logging out](https://auth0.com/docs/logout).  We've logged out at the "Application Session Layer", but not at the "Auth0 Session Layer". We need to send users to the [logout endpoint](https://auth0.com/docs/api/authentication#logout) to do that.

This might need work in OAuthenticator.

**Comment by damianavila** [comment]
> This might need work in OAuthenticator.

Globus case seems relevant: https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/globus.py#L21

**Comment by GeorgianaElena** [comment]
> Globus case seems relevant: https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/globus.py#L21

I think so too! Maybe all we need is to write our own logout handler (another useful comment about this [here](https://github.com/jupyterhub/oauthenticator/issues/107#issuecomment-690249793)). I will give this a try today and see how it goes.

**Comment by damianavila** [comment]
> Maybe all we need is to write our own logout handler (another useful comment about this here).

That sounds like the way to go!

>  I will give this a try today and see how it goes.

Super! Thx.
