### ISSUE TITLE
AVC - avc.cloudbank.2i2c.cloud

### ISSUE THREAD

**Issue by ericvd-ucb** [2i2c-org/pilot-hubs#454]
# Background

Community College in Lancaster CA

# Setup Information

- **Hub auth type**: 
What is our plan for Microsoft campuses - just get them to make google accounts?

- **Hub administrators**: 
rbiritwum@avc.edu
James Brownlow <jbrownlow@avc.edu>,
William Kitto <wkitto1@avc.edu>,

- **Hub url**: 
rbiritwum@avc.edu
- **Hub logo**: 
- **Hub logo URL**: 
- **Hub type**: 
education - community college - data 8 
- **Hub cluster**: 
- **Hub image**: 

# Important Information

- **Link to leads issue**: 
- **Hub config name**: 
- **Community champion**: 
@sean-morris 
- **Hub start date**: 
- **Hub end date**: 
- **Hub important dates**: 

# Deploy To Do

- [ ] Initial Hub deployment
- [ ] Administrators able to log on
- [ ] Community Champion satisfied with hub environment
- [ ] Hub now in steady-state

**Comment by yuvipanda** [comment]
@ericvd-ucb @sean-morris we could have them make username / passwords instead of using google auth?
