### ISSUE TITLE
Provide better error on failed login

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#46]
We require admins to add each user they wanna permit into the admin
panel. When users who haven't been expressly added, they get a standard
`403 Forbidden` error. 

This page should be a little more informational, and contain information
on why they couldn't log in, and asking them to contact the admins
to get them added. To begin with, I don't think we need to expose who
the admins are, but we can add that optionally later if needed.

**Comment by yuvipanda** [comment]
We will need to override https://github.com/jupyterhub/jupyterhub/blob/master/share/jupyterhub/templates/error.html in our templates I think.

**Comment by yuvipanda** [comment]
@GeorgianaElena this is done, right?

**Comment by GeorgianaElena** [comment]
@yuvipanda, yeah, this should be fixed by https://github.com/2i2c-org/pilot-homepage/pull/2. I forgot to reference this for closing. Closing it now. Thank you!
