### ISSUE TITLE
Document our PDF generation options

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#48]
A lot of workflows require downloading notebooks as PDF. There are
quite a few ways to do this, and we should provide clear guidance 
on what they are.

[Berkely's DataHub Issue](https://github.com/berkeley-dsep-infra/datahub/issues/1461)
has more details.

I want us to provide:

1. Regular, LaTeX based nbconvert PDF generation. The default
2. [betatim's](https://github.com/betatim) [notebook-as-pdf](https://github.com/betatim/notebook-as-pdf),
   which uses Chrome for a more HTML native PDF generation
3. Filtered PDF output, via something like [otter-grader export](https://otter-grader.readthedocs.io/en/latest/pdfs.html).
   Very useful when you are grading only some of the parts of a notebook.
   Depends on (1)

**Comment by choldgraf** [comment]
Are 1 and 2 already available? If so I will document them

**Comment by yuvipanda** [comment]
@choldgraf I think (1) is available already, (2) not yet.

**Comment by choldgraf** [comment]
closed in https://github.com/2i2c-org/pilot/commit/5a9ab469d87aeb5704de7e6379d7a650ca3c7625

opened https://github.com/2i2c-org/pilot-hubs/issues/59
