### ISSUE TITLE
New Hub: 2 Sigma K-12 education company

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#486]
# Background

At the DSEP workshop we were introduced by @ericvd-ucb to a young company that provides data science curricula meant for K-12 classrooms. They wish to run courses similar to Data 8, but are hoping to partner with another organization to provide expertise around the cloud infrastructure for their Jupyter environments.

They have their own AWS credits, and have a relatively small cohort of users (maybe 50 people at most), and were interested in working with the 2i2c pilot hubs.

This is a bit of a special case, as they are a company not an educational institution. Though they are probably similar in spirit to a private university (which Peddie academy is, and we are running hub infrastructure for them). I believe they're interested in paying for infrastructure in general, though they'd be happy to work with the pilot setup to get to know how things work in the meantime.

# Setup Information

- **Hub auth type**: 
- **Hub administrators**: 
- **Hub url**: 
- **Hub logo**: 
- **Hub logo URL**: 
- **Hub type**: 
- **Hub cluster**: 
- **Hub image**: 

# Important Information

- **Link to leads issue**: 
- **Hub config name**: 
- **Community champion**: 
- **Hub start date**: 
- **Hub end date**: 
- **Hub important dates**: 

# Deploy To Do

- [ ] Decide whether they are in-scope for our hub pilot.
- [ ] Initial Hub deployment
- [ ] Administrators able to log on
- [ ] Community Champion satisfied with hub environment
- [ ] Hub now in steady-state

**Comment by damianavila** [comment]
> Decide whether they are in-scope for our hub pilot.

What we need to know and discuss to take this decision?
From your description, it seems something inside the 2i2c scope, maybe? Or are we extending the 2i2c scope if we work with them?

**Comment by choldgraf** [comment]
I think that they're in-scope from a content perspective (they focus on K-12 education, do data science work, etc). The main question to me is whether it's OK for us to run a hub for them pro-bono, given that they are a for-profit entity.

After asking about the AWS deployment story (which is where their credits reside), I feel like this should be our decision criteria:

- If we would value having another hub to test out the AWS deploy infrastructure, so that we learn how it is working, use it to improve docs, etc, then we could offer to run their infrastructure on AWS using their credits.
- If instead we'd rather minimize the amount of time needed to run this hub, then we offer them a pro-bono GCP hub running a lightweight environment.
- Once we can process payments, we plan to transition them to a "regular" paid plan.

Does that sound reasonable?

**Comment by damianavila** [comment]
Sounds reasonable to me.

My first gut reaction would be to use their credits and then transition to a regular plan.
Although, I might be biased because of their for-profit nature...

**Comment by yuvipanda** [comment]
What did we decide to do with this?

**Comment by damianavila** [comment]
@choldgraf, maybe, have more info?

**Comment by choldgraf** [comment]
I think that we can close this - they kinda dropped off, and this was not a super promising lead (they are a start-up, so arguably outside the scope of 2i2c)
