### ISSUE TITLE
Make the dask workers be spot instances in carbonplan

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#490]
The CarbonPlan hub dask workers should be spot instances in order to keep their costs down. This requires fiddling with the configuration until it works properly

**Comment by choldgraf** [comment]
I've heard from Joe that this is important to implement so that the CarbonPlan hub doesn't incur too much extra costs (the AWS bill they got for July was quite large, apparently). I'm going to mark this as `priority` to signal boost a bit.

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/pilot-hubs/pull/605 does this. I've deployed and tested it.
