### ISSUE TITLE
Provide feedback on the support steward proposal

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#495]
https://docs.google.com/document/d/17Kj_FbtVMl32TEcfvCp18fF1SEiBjVOhCswdidUytgM/edit?usp=sharing

**Comment by choldgraf** [comment]
cc @2i2c-org/tech-team - would love feedback

**Comment by sgibson91** [comment]
I really like this! 🙌🏻

**Comment by GeorgianaElena** [comment]
I really like the idea too! :sunny: 

Another support-related aspect that might be related and I think we should also sort out (not necessarily as part of this proposal) is being around during the "hub important dates" (I think there was a calendar for these too?)
