### ISSUE TITLE
Document how to self-serve images

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#505]
# Background

With https://github.com/2i2c-org/peddie-image and https://github.com/2i2c-org/farallon-image/, we're starting to use https://pilot.2i2c.org/en/latest/admin/howto/configurator.html so hub admins can self-serve image changes. We should document:

- [ ] Different image selection strategies, and how we decide to use
- [ ] Setting up a new self-serve image repo (for 2i2c engineers)
- [ ] Documentation for hub admins to change and deploy their new environment

Related: https://github.com/yuvipanda/jupyterhub-configurator/issues/1

**Comment by choldgraf** [comment]
I think this is a duplicate of https://github.com/2i2c-org/pilot-hubs/issues/630
