### ISSUE TITLE
Generate a 'status' page for 2i2c pilot hubs

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#52]
Whenever users encounter an issue, first question is 'just me or everyone?'.
Service-wide 'Status pages' are very useful for this - see [GitHub's](https://www.githubstatus.com/).

We should have one for all 2i2c hubs.

**Comment by choldgraf** [comment]
Agree - could just be a page at 2i2c.org/pilot/status that links a grafana chart?

**Comment by yuvipanda** [comment]
Closing as a dupe of https://github.com/2i2c-org/pilot/issues/46
