### ISSUE TITLE
2i2c Service Outage for Openscapes Hub

### ISSUE THREAD

**Issue by erinmr** [2i2c-org/pilot-hubs#521]
Hi @yuvipanda - I added a comment to our [closed issue,](https://github.com/2i2c-org/pilot-hubs/issues/363#issuecomment-881587416) but wanted to make sure you all saw this. We are getting a service outage on our hub. Is this an issue on your side or something we troubleshoot?

**Comment by yuvipanda** [comment]
@erinmr taking a look now!

**Comment by yuvipanda** [comment]
@erinmr can you try now? Should be fixed

**Comment by amfriesz** [comment]
The hub is working for me now.

**Comment by erinmr** [comment]
Thank you so much, @yuvipanda! It's working for me too

**Comment by yuvipanda** [comment]
Thanks for reporting it here, @erinmr! Glad we could get it sorted. We'll write an incident report soon
