### ISSUE TITLE
Upgrade to z2jh 1.1.0+

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/pilot-hubs#539]
# Summary

Task: to upgrade to z2jh 1.1.0 ([CHANGELOG](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/CHANGELOG.md))

- hub.services.<service>.apiToken is now automatically generated, and a bug in jupyterhub is fixed so it can be set to a blank even if it wouldn't be autogenerated by z2jh. I recall @GeorgianaElena ran into this bug before and perhaps there is some cleanup that can be done.
- I believe we install a specific commit of kubespwner that previously wasn't released in the pilot-hubs hub image, but that won't be needed any more
- KubeSpawner now intelligently sort environment variables to help them resolve. This can make our logic to set SCRATCH_BUCKET environment variables less complicated if i recall correctly.

**Comment by damianavila** [comment]
@consideRatio, IIRC, these ones were not addressed in #635:
 
* hub.services..apiToken is now automatically generated, and a bug in jupyterhub is fixed so it can be set to a blank even if it wouldn't be autogenerated by z2jh. I recall @GeorgianaElena ran into this bug before and perhaps there is some cleanup that can be done.
* KubeSpawner now intelligently sort environment variables to help them resolve. This can make our logic to set SCRATCH_BUCKET environment variables less complicated if i recall correctly.

Should we re-open this one, or open new issues for the remaining tasks?

**Comment by consideRatio** [comment]
Thanks @damianavila I opened #658 to represent those small tasks.
