### ISSUE TITLE
Debugging setup of grafana

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/pilot-hubs#543]
I would like to deploy grafana to coessing.pangeo.2i2c.cloud so that we and admins can monitor activity. I am following @yuvipanda's instructions [here](https://github.com/2i2c-org/pilot-hubs/pull/533#issuecomment-883290848). Here are the steps I'm taking:

1. From PR https://github.com/2i2c-org/pilot-hubs/pull/456, I have checked out the `support/secrets.yaml` file, and the updated `.sops.yaml` and `deployer/hub.py` files.
2. I am running `python deployer deploy-support pangeo-181919` and everything passes
3. I have added the external IP of `support-ingress-nginx-controller` to the grafana.pangeo.2i2c.cloud DNS entry and I can see the login page at that address

**Problem:**

When I enter username `admin` and the decrypted admin key from `support/secrets.yaml`, I am told this is an incorrect password. Have I missed something?

**Comment by yuvipanda** [comment]
@sgibson91 Did you do a prior deploy without the secrets.yaml file? If so, grafana autogenerates a password it doesn't tell you about (grumble grumble). Delete the `support-grafana` secret in the `support` namespace and try running deploy-support again?

**Comment by sgibson91** [comment]
Hmmm yeah, this doesn't seem to work. I think I'll try removing the support chart and reinstalling with the admin password from the start.

**Comment by sgibson91** [comment]
Fixed!

Note to self: I was not being as clever as I thought I was being when I ran the below

```
sops -d -i support/secrets.yaml && cat support/secrets.yaml | pbcopy && sops -e -i support/secrets.yaml
```

The `cat` probably needs to be a `jq` instead - but that's beside the point
