### ISSUE TITLE
Have a state label on PRs

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/pilot-hubs#552]
# Summary

Usually, an open PR in `pilot-hubs` repo can be in one of this states:
- not-tested
- deployed on the staging hub
- deployed in prod, either for all the hubs if it's a general change, or to one specific hub

# User Stories

I believe there is value in knowing in which state a PR is, as it can help the @2i2c-org/tech-team review, test and merge PRs more effectively. 

# Acceptance criteria

When we decide upon if we want such labels and which ones should we use to describe a PR's state.

# Important information

# Tasks to complete

- [ ] Decide if such `state` labels would be useful
- [ ] Add and use the new labels

**Comment by sgibson91** [comment]
I like this idea! How about one label to describe the state as you suggest, and another to describe the scope: single hub vs whole cluster?

State labels:
- `state: untested`
- `state: deployed to staging`
- `state: deployed to prod`

Scope labels:
- `scope: single hub`
- `scope: whole cluster`

Any PR affecting infrastructure can have one, **and only one**, label from each group?

**Comment by GeorgianaElena** [comment]
> How about one label to describe the state as you suggest, and another to describe the scope: single hub vs whole cluster?

This combination of `state` and `scope` is perfect, @sgibson91!

**Comment by choldgraf** [comment]
I think this is a good idea to help others have visibility, and to make things less ambiguous.

My main concern is that we'll miss updating a PR, and it will have a label that is _explicit but wrong_. We might have more faith that it is correct because there is a label, and this will mislead us. Do we foresee that posing a strong problem?

Also FYI I'm adding this to the "review" column on the activity board so others know to give feedback!

**Comment by damianavila** [comment]
> Do we foresee that posing a strong problem?

This is a good point... I have worked with state and scope labels before and you need most (if not all the) people to be "religious" about labels to make this work out well.

**Comment by sgibson91** [comment]
We use labels in the Turing Way to denote state of review (unreviewed, partially-approved, approved, requested changes, etc) but these are managed automatically by a bot https://github.com/pr-triage/app

**Comment by damianavila** [comment]
That nice! At the time I established labels to have some issues and PRs management in Bokeh, there were not bots nor GitHub apps (maybe no even a nice API to work with labels?). With a bot in place, I am on now :+1:

**Comment by sgibson91** [comment]
> even a nice API to work with labels?

If we wanted something bespoke, I think this would be easily achievable with something like [ghapi](https://github.com/fastai/ghapi)

**Comment by choldgraf** [comment]
@GeorgianaElena now that we have have [some basic merging and review guidelines](https://pilot-hubs.2i2c.org/en/latest/contributing/code-review.html), do you think that this one is still needed? I think we have two options here:

1. Try and work in a process for using GitHub PR labels in our review/merge process
2. See if this process works well enough on its own to avoid the confusion about when PRs are deployed

What do you think?

**Comment by GeorgianaElena** [comment]
@choldgraf, now that the PR creator is the same person as the one responsible for the merge/deploy,  my opinion is to go with option 2 and revisit using PR labels only if we feel the current process doesn't work well enough and labels could bring more value to it.

Please feel free to close this issue if you and others agree :dart:

**Comment by choldgraf** [comment]
that sounds good @GeorgianaElena - let's revisit this one if we find that the current system still leaves some ambiguities or could be improved with labels!
