### ISSUE TITLE
Automate deleting old charts and updating dependencies

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/pilot-hubs#556]
### Summary

When trying to manually deploy a new 2i2c hub, I ran into a bug caused by our rename from `base-hub` to `basehub` from some time ago and the presence of an outdated chart with the old name.

To prevent this from repeating, when manually deploying a hub, we should automatically:
- if there's a version mismatch
  - delete the `charts/` dir
- run `helm dep up`
- continue deploying the hub/s 

### Benefit

This will reduce engineer confusion if there's a mismatch between local charts + whatever is being used in our deployer script. We've already had a few reports where this bug bit people and made them lose a few hours so this would resolve that.

### Implementation details

This will be an update to our `deployer.py` tool here: https://github.com/2i2c-org/pilot-hubs/tree/master/deployer

We should first just automatically run `helm dep up` as a part of our deploys, as a stop-gap solution to this problem. After that, we should decide how to add in a check for whether we *need* to run `helm dep up`.

### Tasks

- [x] https://github.com/2i2c-org/pilot-hubs/pull/705
- [x] Decide whether to add the conditional check as part of this issue or to open a new medium-term issue

**Comment by damianavila** [comment]
OK, this one has bitten me again I am looking at it a little bit more closely...

The first item is proposing:

> if there's a version mismatch
> delete the charts/ dir

When I look into the `helm dep list` in my local repo for the basehub and daskhub charts:

```
helm dep list
NAME      	VERSION	REPOSITORY                              	STATUS       
jupyterhub	1.1.3  	https://jupyterhub.github.io/helm-chart/	wrong version
```

```
helm dep list
NAME        	VERSION	REPOSITORY                              	STATUS       
basehub     	0.1.0  	file://../basehub                       	wrong version
dask-gateway	0.9.0  	https://dask.org/dask-gateway-helm-repo/	ok     
```      

This is great because we see there is a wrong version!
But if I try to get the output as json

```
helm dep list --output json
Error: unknown flag: --output
```

Buuu...
And a big PR for that seems to be stale: https://github.com/helm/helm/pull/8077

Since we are unconditionally updating the support chart here: https://github.com/2i2c-org/pilot-hubs/blob/master/deployer/hub.py#L109

What do you all think about just fetching the basehub and daskhub charts just before performing the helm upgrade without checking any status/version? That is what we are essentially doing on the CI: https://github.com/2i2c-org/pilot-hubs/blob/master/.github/actions/deploy/action.yml#L14 (although we start from a clean state there).

**Comment by yuvipanda** [comment]
> What do you all think about just fetching the basehub and daskhub charts just before performing the helm upgrade without checking any status/version?

I think it's an improvement over status quo. Unfortunately it just adds a lot of time to each deploy, slowing down testing...

**Comment by damianavila** [comment]
> I think it's an improvement over status quo. Unfortunately it just adds a lot of time to each deploy, slowing down testing...

The alternative would be to parse that output somehow to prevent unneeded updates... maybe ugly but a good enough compromise?

**Comment by choldgraf** [comment]
Just a quick note that the face we have a few "I've wasted a few hours being bitten by this" responses here makes me feel like this one is worth prioritizing. Is this one of those situations like "we collectively discuss and spend 4 hours now in order to save ourselves 30 hours later"?

**Comment by damianavila** [comment]
> this one is worth prioritizing.

I agree. It is something to should pick up sooner than later, IMHO.

**Comment by choldgraf** [comment]
Is this something that we could automate at all with a GitHub Action that runs on a CRON job or something? Is there config in this repo that could tell us if a hub's chart is out-dated? Or is this something that we'd need to build in as a check in the deploy script itself?

**Comment by damianavila** [comment]
> Or is this something that we'd need to build in as a check in the deploy script itself?

I think that is the case...

**Comment by sgibson91** [comment]
> > I think it's an improvement over status quo. Unfortunately it just adds a lot of time to each deploy, slowing down testing...
> 
> The alternative would be to parse that output somehow to prevent unneeded updates... maybe ugly but a good enough compromise?

I'm personally +1 on just adding `helm dep up` straight into the deployer and eating the extra time. It's not like we're talking about a 10s second script increasing to minutes long, more like a minutes long script is gonna take a few more minutes. I'm already in the habit of brewing some tea during deploys anyway ☕ 😁

**Comment by yuvipanda** [comment]
Sorry I wasn't clear earlier - +1 to adding helm dep up, but hopefully we can keep this open until we do it conditionally too :)

**Comment by yuvipanda** [comment]
I do want to investigate why deploys take minutes though - it has always bugged me. The process should be definitely much faster, given the actual work helm is doing.

**Comment by choldgraf** [comment]
OK I've updated the top comment with what I think are the next steps here 👍

**Comment by sgibson91** [comment]
I opened https://github.com/2i2c-org/pilot-hubs/pull/705 to address the first action point

**Comment by damianavila** [comment]
#705 is already merged but keeping this one open for the conditional check.

**Comment by choldgraf** [comment]
Should we re prioritize this issue to be lower now? The underlying problem is now resolved, though the conditional would help us save time, so i guess the question is: how annoying is it to have to wait the extra time for each deploy?

**Comment by sgibson91** [comment]
I'm +1 as reprioritising as low impact. I personally do not find the extra time annoying.
