### ISSUE TITLE
Document how to download your own data

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#56]
We currently have [jupyter-tree-download](https://github.com/ryanlovett/jupyter-tree-download/)
installed. This should be more prominent & documented, so users can download their
own data easily.

**Comment by choldgraf** [comment]
Nice - will add these do the pilot docs 👍 

I added https://2i2c.org/pilot/about.html#what-happens-if-i-want-to-move-off-of-a-2i2c-hub yesterday but it is super barebones so will be helpful to add content like this

**Comment by yuvipanda** [comment]
Thanks, @choldgraf :)

**Comment by choldgraf** [comment]
closed in https://github.com/2i2c-org/pilot/commit/5a9ab469d87aeb5704de7e6379d7a650ca3c7625
