### ISSUE TITLE
Add JupyterHub admin users to CarbonPlan hub

### ISSUE THREAD

**Issue by jhamman** [2i2c-org/pilot-hubs#566]
# Summary

I'd like to add 3 folks to the list of JupyterHub admins on the CarbonPlan hub. Those are:

- @jhamman (me!)
- @orianac
- @tcchiao 

# User Stories

- We need the ability for a few folks on our core team to administer JupyterHub sessions.

# Acceptance criteria

- All users listed above should be able to access the admin dashboard on the hub

# Important information

# Tasks to complete

- [ ] add users to list of hub admins

**Comment by choldgraf** [comment]
@jhamman are you not already an admin user? Generally speaking after the first has been added, they can add new admins via the jupyterhub UI

**Comment by jhamman** [comment]
I am not currently an admin user. Looking at the carbonplan hub config, I don't think anyone is an admin user.

**Comment by choldgraf** [comment]
Gotcha - I think this PR will do the trick: https://github.com/2i2c-org/pilot-hubs/pull/567

I've added you as an admin and you can then add others once that PR is merged.
