### ISSUE TITLE
Host folder of HTML files JupyterHubs simple via HTTP proxy

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#58]
I have been thinking more about our conversations around creating custom pages for things like generating nbgitpuller links / environments / etc. It gave me an idea and I'm curious what @yuvipanda thinks about it:

What if we made it really easy for hub administrators to host a static website at some path on their hub (maybe default is `myhub.org/docs`. Then, that can be a single extension point that hub administrators could use for building out their hub-specific documentation. Rather than us finding ways to keep extending the JupyterHub-specific interfaces, we could just add a `docs` option to each JupyterHub toolbar.

It would also let us do things like turn the [nbgitpuller link generator](https://jupyterhub.github.io/nbgitpuller/link) into a Sphinx extension (if the docs were hosted with Sphinx) so that administrators could include a link generator on their hub simply by putting a page like this in their docs:

at `myhub.pilot.2i2c.cloud/docs/link-generator`:

````
# My page title
Link generator will be embedded below.

```{nbgitpuller-generator}
:hub: myhub.org
```
````

# For current plan, see https://github.com/2i2c-org/pilot-hubs/issues/58#issuecomment-707367367

**Comment by choldgraf** [comment]
Maybe one simple approach is to make a simple HTTP server serve a pre-defined folder on the hub, and then provide instructions for how administrators can push the HTTP content of their choice to that folder?

**Comment by yuvipanda** [comment]
We could allow pointing to a different git repo than github.com/2i2c-org/pilot-homepage, so they can push files there to override. I like this more than a directory on the hub. What do you think?

**Comment by choldgraf** [comment]
Mmmm, I'm not sure - mostly my concern is that hand-editing HTML is not something most users will be comfortable with, much less following the instructions in `pilot-homepage`. On the other hand there's a huge world of documentation and skillsets out there for building static websites for documentation, so I was trying to think of a way to make it easier to connect that world with a JupyterHub.

The other thing I imagined is that some hubs may wish to have hub-specific websites or documentation that we do not maintain. E.g. a course will want to have a page with syllabus, links, updates, etc.

Perhaps another option is to document for people how they could add a *redirect* for `myhub.pilot.2i2c.cloud/docs` to an external documentation source?

**Comment by colliand** [comment]
I write to share some thoughts on documentation. These may be orthogonal to the discussion above. 

It may be useful for new users to arrive to the hub with an initial notebook or an initial folder. An initial notebook that illustrated a few of the things that could be done with the hub. The notebook could have pointers to R Studio, nbgitpuller, etc. 

A fancier variation? Can we auto-deploy a JupyterBook resource located at `<hub>/docs` with a variable that replaces references to the hub throughout the JupyterBook with `<hub>`? Fancier things could perhaps be done with the logo. That docs directory could then be made accessible to the admin users so they could make edits. I am not sure about how to handle the web hosting for that docs site.

**Comment by choldgraf** [comment]
> It may be useful for new users to arrive to the hub with an initial notebook or an initial folder. An initial notebook that illustrated a few of the things that could be done with the hub. The notebook could have pointers to R Studio, nbgitpuller, etc.

For sure - I think that in the short term we should create a notebook or two that helps people get started with the hub and make this part of the default image. Eventually, this should be something that hub administrators can customize themselves as part of their hub-specific environment generation.

> Can we auto-deploy a JupyterBook resource located at <hub>/docs with a variable that replaces references to the hub throughout the JupyterBook with <hub>?

That is an interesting idea - I wonder, if we restricted people to only be able to use Jupyter Book, this might be a more straightforward thing to maintain. Eventually what I'd like to happen is connect Jupyter Book content with a specific hub so that they can get live code via `thebe` that is powered by their hub's kernels (but I'm not sure how to do this from a credentials point of view...maybe it'd be easier if the book itself were hosted inside the hub). This feels like a more longer-term goal though.

**Comment by choldgraf** [comment]
After discussing this with @yuvipanda, the easiest first step would be to allow users to point us to a repository where there is a collection of HTML files. We would then serve those HTML files via a simple proxy at `docs/`. This would remove us from the "HTML files building" picture, which means there is one-less thing we have to worry about supporting/breaking/etc.

So we'd need to

- document for users how they can build a collection of HTML files and host them in a place online
- write the configuration / deployment infra to host a collection of HTML on the hub
- document best-practices for how people can connect their content with the hub

**Comment by yuvipanda** [comment]
Update: @GeorgianaElena is working on this right now. Technical details also found in #163.

**Comment by yuvipanda** [comment]
Georgiana has completed this!
