### ISSUE TITLE
Use a matrix job to deploy our clusters

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#581]
For sure! I was going to suggest using something like this action to set a conditional on the paths changed https://github.com/dorny/paths-filter
So we maintain the same behaviour of not doing a deploy when nothing's changed, but we can consolidate into a single workflow file and new clusters can just be added to the matrix element list.

_Originally posted by @sgibson91 in https://github.com/2i2c-org/pilot-hubs/pull/569#discussion_r683353363_

**Comment by sgibson91** [comment]
The current behaviour is that if **any** of the below filepaths change, even if a `.cluster.yaml` file **doesn't** change, we still deploy right?

https://github.com/2i2c-org/pilot-hubs/blob/845c961b3ee95a9f919a7d4c2086fdc8901baa5a/.github/workflows/deploy-2i2c.yaml#L7-L11

I am testing the workflow over here https://github.com/sgibson91/test-pathfile-conds-gh-actions

**Comment by choldgraf** [comment]
This sounds like a great idea to me - would definitely improve our DRY for these deploy auto-actions

**Comment by sgibson91** [comment]
I've just opened #582 which would _replace_ this PR if merged because it already contains the clusters @yuvipanda was adding in here
