### ISSUE TITLE
Authenticate users with GitHub Teams membership in Pangeo Hub

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#598]
### Description

The Pangeo project currently uses GitHub Team-based authentication (so you add a user to a GitHub Team, and that person automatically now gains access to the hub). We should support this workflow on the Pangeo Hub.

Currently, we use the [auth0 authenticator](https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/auth0.py) to support all our auth providers (github, google, etc). It doesn't support restricting auth based on team or org membership. We should find a way around that.

### Benefit

This primarily benefits the Pangeo project, which is reason enough to do this. However, the process of using GitHub Teams for authentication is probably generally useful across many communities, so this will be more broadly applicable.

### Implementation details

There are two potential ways to do this:

1. Use `Auth0` for our authentication. This would be the simplest if we could get it working.  [Here is the Pangeo configuration for Auth0](https://github.com/pangeo-data/pangeo-cloud-federation/tree/e0b8afdd5571a8a1e68b4b7a33b789703a97ac7f/auth0). Issue to track this in the future https://github.com/2i2c-org/pilot-hubs/issues/698
2. Support plain OAuthenticator in our deployment, activate it for the Pangeo Hub, and configure it to use GitHub Teams (https://github.com/2i2c-org/pilot-hubs/issues/625). This is more complex because now we are deviating from the standard Auth0 pipeline we've used elsewhere.

### Tasks to complete

- [x] https://github.com/2i2c-org/pilot-hubs/issues/625
- [x] Document this setup for how we could deploy this for a general hub. Done in https://github.com/2i2c-org/pilot-hubs/issues/726

**Comment by sgibson91** [comment]
The OAuthenticator bump in z2jh-k8s happened here: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2350

**Comment by yuvipanda** [comment]
We don't support using anything other than auth0 via OAuthenticator right now. https://github.com/2i2c-org/pilot-hubs/issues/625 tracks additional work that needs to happen before we can do this.

**Comment by sgibson91** [comment]
This is unblocked now that #706 #726 and #728 have been successfully deployed

**Comment by sgibson91** [comment]
I aim to merge #707 tomorrow morning unless I receive an approving review before then

**Comment by damianavila** [comment]
> unless I receive an approving review before then

Approved 😉
