### ISSUE TITLE
Move CloudBank institutions to the new cloudbank cluster

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#64]
Once #35 happens, we'll probably want to deploy hubs that are funded by CloudBank to `<hubname>.cloudbank.2i2c.cloud` (instead of `.pilot.2i2c.cloud`). This includes

- spelman
- ccsf
- elcamino

I think right now none of these have actual users, so we can probably just delete them and move them over-straightaway. Or, we could use it as an opportunity to document how a hub can be moved between projects.

**Comment by ericvd-ucb** [comment]
Hi - just checking in on the status of this before a meeting tomorrow at 12pm PDT  @yuvipanda

**Comment by choldgraf** [comment]
@yuvipanda when I try to log on I got:

![image](https://user-images.githubusercontent.com/1839645/95919449-75d85500-0d62-11eb-87a0-fa724f18db04.png)

**Comment by ericvd-ucb** [comment]
@choldgraf   Thanks - looks good - do you want me to add you as optional for meeting invite?

**Comment by choldgraf** [comment]
sounds good - @ericvd-ucb were you able to log into the hub successfully or did you get the same error page?

**Comment by ericvd-ucb** [comment]
error page - the spelman.pilot still working though

**Comment by yuvipanda** [comment]
Sorry guys. Investigating this now.

**Comment by yuvipanda** [comment]
@ericvd-ucb @choldgraf ok, looks like this works now and I see folks have logged in. I think I fixed this yesterday without seeing this issue?

**Comment by yuvipanda** [comment]
They're all in the new cluster now.

**Comment by choldgraf** [comment]
very exciting! hooray \o/
