### ISSUE TITLE
Support CILogon with Auth0

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#65]
If we supported CILogon (https://github.com/cilogon) with our Auth0 setup, then we would be able to connect to the login infrastructure of many more academic institutions. 

This should be possible via: https://www.cilogon.org/auth0

**Comment by choldgraf** [comment]
Note that CILogon will only work with organizations that use eduroam. Wageningen might be a good candidate to test this out (https://www.wur.nl/en/Value-Creation-Cooperation/Facilities/Mobile-Device-Support/You-work-or-study-at-an-Eduroam-participant-and-you-bring-your-own-laptop.htm)

**Comment by yuvipanda** [comment]
Closing as dupe of https://github.com/2i2c-org/pilot-hubs/issues/315
