### ISSUE TITLE
New Hub: American University of Paris

### ISSUE THREAD

**Issue by shaolintl** [2i2c-org/pilot-hubs#659]
### Hub Description

The American university of Paris is a liberals arts university in France. A key aspect of the liberal arts approach is the broadening of the students knowledge to more disciplines. The data science program in the American University of Paris is doing exactly that and will allow students to add a new dimension to their studies. The hub is the main tool for achieving that, allowing students from all level a direct access to data science.

### Community Representative(s)

Tomer Libal tlibal@jupyter.org, @shaolintl
Sam Walker, swalker@jupyter.org, @swalker

### Important dates

- 2021-09-20 : We will have a training using the hub during this week
- 2021-05-15 - 2021-08-31 : We will pause using the hub for the summer

### Target start date

2021-09-13

### Preferred Cloud Provider

No preference (default)

### Do you have your own billing account?

- [ ] Yes, I have my own billing account.

### Hub Authentication Type

GitHub Authentication (e.g., @mygithubhandle)

### Extra features you'd like to enable

- [ ] Dedicated Scalable Dask Cluster with [Dask Gateway](https://gateway.dask.org/)

---

# Hub Engineer information

The Hub Engineer should fill in the metadata below when it available. The Community Representative shouldn't worry about this section, but may be asked to provide help answering some questions.

## Deployment information

**Hub ID:**
  `aup`
**Hub Cluster:**
  `pilot`
**Hub URL:**
  `aup.pilot.2i2c.cloud`
**Hub Template:**
  `basehub`

# Actions to deploy

- [x] Engineer who will deploy the hub is assigned
- [x] Deploy information filled in above
- [ ] Initial Hub deployment PR: <link to PR>
- [ ] Administrators able to log on
- [ ] Community Representative satisfied with hub environment
- [ ] Hub now in steady-state

**Comment by choldgraf** [comment]
Thanks @shaolintl for this request! Let us get to work on it. It sounds like you don't have strong preferences for the specific cloud provider (though, in the long term I think you had preferred Azure? Is that right?)

@2i2c-org/tech-team I think that we have two options here:

1. We finish up https://github.com/2i2c-org/pilot-hubs/issues/512 and deploy this hub in Azure on top of a new cluster there (perhaps we create a 2i2c pilot hubs cluster similar to our GCP one?)
2. We deploy this hub in our Google Cloud cluster, and then may have to migrate it to Azure in the future.

I think the answer there largely depends on how quickly @yuvipanda thinks the Azure hub deployment situation can be finished up. Given that we are still working out some kinks there, **my intuition is that we should go with option 2** and deploy in GCP for now. If nobody objects then I'll plan on taking that action this week and deploy the hub there, but if somebody really wants to try deploying this on Azure, I'm happy to hold off!

**Comment by yuvipanda** [comment]
@choldgraf Let's go with option (2) for now, and consider moving it to Azure in a month or two?

**Comment by choldgraf** [comment]
Sounds good - I'll try deploying this hub on GCP this sprint (it is good to know that this won't prevent us from using AzureAD necessarily).
