### ISSUE TITLE
Demo Hub

### ISSUE THREAD

**Issue by jamesgspercy** [2i2c-org/pilot-hubs#68]
I have set up a hub on CloudBank that has really only been used to demonstrate the technology stack.

Could this hub be useful as a demo (showroom) hub that potential clients could be directed to to test out a live hub environment?

Does such a service already exist?

**Comment by choldgraf** [comment]
Nope we don't have a service like this. I think it could be useful! Something that we can give out credentials to but explicitly don't recommend people rely on for the whole semester or for a class. We could also populate it with few materials that show off the environment etc.

Does the hub you set up already live somewhere? I think we could set something like this up at `demo.cloudbank.2i2c.cloud`. @yuvipanda and I were planning to set up a new 2i2c domain for the CloudBank collaboration hubs `<hubname>.cloudbank.2i2c.cloud` so this could be a nice way to get people started there.

**Comment by jamesgspercy** [comment]
This sounds great!

Currently the hub is using `datahub.cloudbank.org` maybe we could direct a new alias to this hub?

@yuvipanda @choldgraf I like your idea of a `cloudbank.2i2c.cloud` domain for these hubs.

**Comment by choldgraf** [comment]
`cloudbank.2i2c.cloud` now exists! Though the `datahub.cloudbank.org` does not currently point to it.

A couple quick thoughts about a demo hub:

- I think we'd want it to be as painless as possible to get access (e.g. no sign-up process etc, we just send somebody there and they get started)
- We probably want it building on the same build infrastructure as the other hubs in the pilot. That way any changes / improvements in the pilot also show up in the demo so users aren't surprised at the change.

**Comment by colliand** [comment]
Excellent! Is there a scope limitation here? I don't envision a massive onslaught of users but wish to confirm whether CloudBank may have specified any user scope targets or limitations. 

I personally wish to move my own cloud-hosted JupyterHub usage away from my current service (ubc.syzygy.ca) and onto a 2i2c-managed hub. My hope is to use a "batteries included" 2i2c hub that could also be used for demos with others. I am interested in advice.

**Comment by jamesgspercy** [comment]
Thanks for this @choldgraf and @yuvipanda!

Hi @colliand! I'm currently working on this. I'll be in touch once I have a better idea about scope.

My hope for the datahub.cloudbank.org page is to transform this into a gallery/showcase and list all the hubs hosted on CloudBank including this demo hub.

**Comment by choldgraf** [comment]
@jamesgspercy if you want a semi-up-to-date list check out here:

https://2i2c.org/pilot/infrastructure.html#a-list-of-current-hubs

and here is the code I'm using to generate the list in Sphinx:

https://github.com/2i2c-org/pilot/blob/main/conf.py#L56

**Comment by choldgraf** [comment]
how about we create a new hub at `demo.cloudbank.2i2c.org` and use it as a showcase hub? To start with we can use Google OAuth to let people log on, and if we figure out a more liberal authentication mechanism in the future then start to use that. (e.g. for this hub we might just want a simple username/password that we can distribute as we wish?)

**Comment by colliand** [comment]
I like this if Cloudbank is on board! If not, let's do it alone with a corresponding change in the URL.

**Comment by jamesgspercy** [comment]
Thanks @choldgraf `demo.cloudbank.2i2c.org` works. Google OAuth is great for now.

Thanks for the code, I'll give it ago!

**Comment by choldgraf** [comment]
I've tried creating `demo.cloudbank.2i2c.cloud` but this seems to raise a filesystem mounting error right now. Perhaps others can try and see if this error pops up for them as well? I opened up #83 to discuss

**Comment by jamesgspercy** [comment]
@choldgraf I have just tried and I get the same mounting error.

**Comment by yuvipanda** [comment]
This exists now, I think!
