### ISSUE TITLE
[Incident] RStudio loading tidyverse throws a timedatectl / systemd error

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#692]
# Summary

We got some weird bug reports from the U. Toronto folks. They have a bug in RStudio where trying to import the tidyverse has suddenly created this esoteric error:

```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down

Warning message:
In system("timedatectl", intern = TRUE) :
  running command 'timedatectl' had status 1
```

this is also something that only **sporadically** happens. I confirmed these things with the community rep:

- This is a new problem that has only recently come up
- Not everybody runs into this problem, only some people.
- For people that have this issue, it only happens sometimes, and always with that "timezone" error.
- If you keep re-running the code after a few tries, it usually starts to work normally again.

The UC Berkeley DataHub also had a similar issue here: https://github.com/berkeley-dsep-infra/datahub/issues/2255

- Freshdesk ticket: https://2i2c.freshdesk.com/a/tickets/22
- Hub: University of Toronto (utoronto.2i2c.cloud)

UC Berkeley also had a similar issue with the DataHub: https://github.com/berkeley-dsep-infra/datahub/issues/2255

## Timeline (if relevant)

All times in US/Pacific.

### 2021-09-14

Community Representative reported that importing the `tidyverse` was throwing the error mentioned above, and that `knitr` would not work as a result. They mentioned that this is a sporadic problem that doesn't always happen, and also seems to resolve itself on its own after running the same code many times.

### 2021-09-15

Investigation of this issue uncovered a few similar issues others have experienced

- https://community.rstudio.com/t/timedatectl-had-status-1/72060/3
	- The recommended fix here was:
	> I would try setting your timezone using the TZ variable in your .Renvrion file:
    >
    >  ```
    >  TZ="America/Los_Angeles"
    >  ```
- UC Berkeley similar issue: https://github.com/berkeley-dsep-infra/datahub/issues/2255

Running `timedatectl` from the command line returns the same issue

### 2021-09-20

PR to manually set TimeZone in user image: https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/102

### 2021-09-22

We tried to deploy this fix to production (https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/103) but this raised the bug described in #702 so we must resolve that before moving forward.

### 2021-09-24

After running into a more complex issue with RStudio / R pinning, we finally got this one resolved.

PR to resolve the R pinning bug: https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/112
PR that merged the TZ fix: https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/105 + https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/102/files

## What went wrong

This is a common-ish bug in the RStudio world, and others have run into it before. Our biggest challenge was that we didn't have an easy way to identify it because pre-existing documentation was relatively sparse. Hopefully this issue will be a better record that we can use for reference in the future.

## Where we got lucky

One of our team members had run into this before, and so happened to know what was going on quickly.

### Process improvements

1. Most of the issues here ended up being related to a broader version pinning process, so we've opened incidents about that for follow up https://github.com/utoronto-2i2c/jupyterhub-deploy/issues/106

# Actions

- [x] Incident has been dealt with or is over
  - [x] https://github.com/utoronto-2i2c/jupyterhub-deploy/issues/106
- [x] Sections above are filled out
- [x] All actionable items above have linked GitHub Issues

**Comment by GeorgianaElena** [comment]
@choldgraf :arrow_right:  https://github.com/utoronto-2i2c/jupyterhub-deploy/runs/3673401967 just deployed to prod

**Comment by choldgraf** [comment]
### 2021-09-22

We tried to deploy this fix to production (https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/103) but this raised the bug described in #702 so we must resolve that before moving forward.

**Comment by choldgraf** [comment]
### 2021-09-22

We've resolved the credentials issue described in #702 so we can deploy again. I've updated the environment with a manual TZ variable, but it still needs to be built, pushed, and deployed. This is the issue to track that: https://github.com/utoronto-2i2c/jupyterhub-deploy/issues/106

@GeorgianaElena would you be willing to give this a shot in the morning (maybe in partnership w/ the geoscience packages update)?

**Comment by choldgraf** [comment]
### 2021-09-24

After running into a more complex issue with RStudio / R pinning, we finally got this one resolved.

PR to resolve the R pinning bug: https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/112
PR that merged the TZ fix: https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/105 + https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/102/files

**Comment by choldgraf** [comment]
closing this one as it is now resolved!
