### ISSUE TITLE
Redirecting the test output (to prevent the CI from leaking secrets) is preventing us to get the actual error locally

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/pilot-hubs#694]
### Description

I faced this issue investigating failures at the time to deploy openscapes.
More details here: https://github.com/2i2c-org/pilot-hubs/pull/691#issuecomment-922320344

### Value / benefit

We should be able to easily get the test output when we are working locally whereas we redirect the output in the CI environment.

### Implementation details

A proposal lives in this comment: https://github.com/2i2c-org/pilot-hubs/pull/691#issuecomment-922320344 (check diff) and people showed interest to have this piece as a new PR.

### Tasks to complete

- [x] PR diff with the proposed implementation
- [ ] Discuss details about the env variable that we may use to detect the GitHub env

**Comment by choldgraf** [comment]
Added to the sprint board since @damianavila mentioned he wanted to tackle this in our team update

**Comment by damianavila** [comment]
Verified on production: https://github.com/2i2c-org/pilot-hubs/runs/3738348406?check_suite_focus=true#step:9:190
