### ISSUE TITLE
Remove NoVNC from the launchers

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#73]
I noticed that there's still a "launch desktop" launcher:

![image](https://user-images.githubusercontent.com/1839645/96163701-10ee3d80-0ecf-11eb-9f06-36fc9dbf109e.png)

but it doesn't seem to work (and I believe @yuvipanda said this is expected not to work). I looked in the environment files and couldn't figure out where it was being installed, so opening an issue that we should probably remove it

**Comment by yuvipanda** [comment]
I think this is gone now?

**Comment by choldgraf** [comment]
yes!
